### ISSUE TITLE
Multi-VERB partials

### ISSUE THREAD

**Issue by jennybc** [r-lib/httr2#10]
In wrapper packages, it's common to create thin wrappers around several `httr::VERB()`s, and use a common, e.g., base URL, user agent, token-injecting strategy, etc. Think about the best pattern for facilitating this. Could possibly extend to other API-wide aspects, like batching, retries, throttling. Make it easier to propagate shared data and policies.

**Comment by petermeissner** [comment]
Do you happen to have a link to an example at hand? Out of curiosity, mostly.

**Comment by jennybc** [comment]
Well, no package does exactly what I'm talking about. But bigrquery is a decent example of an API wrapper that creates custom wrappers around all the basic HTTP verbs, in order to share common data and behaviour:

https://github.com/r-dbi/bigrquery/blob/master/R/bq-request.R

**Comment by hadley** [comment]
I think this is already captured in #1 (or at least this is enough of a major design flaw in httr that it'll be considered very early on)
