### ISSUE TITLE
Document how to use resp_body_json() in a package?

### ISSUE THREAD

**Issue by maelle** [r-lib/httr2#105]
I.e. how to avoid the NOTE `Namespace in Imports field not imported from: ‘jsonlite’` (I'm adding a "manual" import :-) ).

**Comment by hadley** [comment]
Hmmm, it doesn't seem quite right to document that here, since it's a standard package thing — you can just add a dummy import like `@importFrom jsonlite read_json`.

**Comment by jennybc** [comment]
Incidentally we just opened an issue where we're developing text to address this in R Packages.

https://github.com/hadley/r-pkgs/issues/828
