### ISSUE TITLE
vectorize url path construction?

### ISSUE THREAD

**Issue by edavidaja** [r-lib/httr2#106]
as in, I was hoping to write

`req %>% req_url_path_append(c("api", "v2", "search", "count"))`

rather than 

```
req %>%
  req_url_path_append("api") %>%
  req_url_path_append("v2") %>%
  req_url_path_append("search") %>%
  req_url_path_append("count")
```

**Comment by jchrom** [comment]
You can do `req %>% req_url_path_append(c("api", "v2", "search", "count"), collapse = "/")`. Though I would like it better if it just worked, without the extra arg.

**Comment by edavidaja** [comment]
it's right there in the docs 🤦🏾
