### ISSUE TITLE
OAuth as a new package?

### ISSUE THREAD

**Issue by sckott** [r-lib/httr2#11]
@jennybc  and I discussed this just a bit in DM's - she suggested opening an issue here. 

The major feature `crul` does not have that `httr` does have is OAuth. It's not a common use case in scientific web resources, so there's not a big push for me to support it. However, it would be great if there was an easy way for `crul` users to incorporate OAuth with a separate package. 

There's only two higher level http libraries now, but surely more http libraries will come along in the future, and maybe they'll even be httr and httr2 co-existing. 

Breaking out OAuth into a separate library that could be integrated into any http library seems to make sense. In python theres https://github.com/oauthlib/oauthlib and ruby has https://github.com/oauth-xx/oauth2 (i may be missing some other libs that are more widely used)

From what Jenny tells me, OAuth in httr is pretty integrated into the package, so maybe it isn't that easy to do?

**Comment by cderv** [comment]
I really like this idea. This would also allow to support more `grant_type`. 

Just sharing experience here. For now, httr is compatible with Authorization Code Grant using `authorization_code` grant type and Client Credentials Grant using `client_credentials` grant type
but there is still Resource Owner Password Credentials Grant missing which uses `grant_type = "password"` 

Having worked on support for _client credential_ in httr, I can relate to the "pretty integrated" state currently. However, implementing closely the RFC standard to help create the correct parameters and request method for OAuth mechanism seems feasible. My thought are more toward a package to help build other packages rather a package for the user to complete another package.

If anything start on this, I am willing to help if needed.

**Comment by hadley** [comment]
I don't think it's going to be worth pulling out in to a separate package, but OAuth will be much much more flexible in httr2.
