### ISSUE TITLE
Questions about secret management

### ISSUE THREAD

**Issue by ramiromagno** [r-lib/httr2#114]
Thanks for the this new incarnation of `{httr}`! I had used `{httr}` before,  and it was really helpful but now `{httr2}` is even better :)

I had written a few API wrappers in the past, but all were accessing public web APIs and there was no need for authentication. Now I'm trying to write my first wrapper using authentication with `{httr2}`. I just read the vignette [Wrapping APIs](https://httr2.r-lib.org/articles/wrapping-apis.html) and I have one question about secret management. I hope you may clarify.

Under [Secret Management](https://httr2.r-lib.org/articles/wrapping-apis.html#secret-management) section, you start by introducing the `secret_encrypt()`, `secret_decrypt()` and `secret_make_key()` functions as an approach to deal with (encrypted) secrets in the source code. You first toy example is for a putative secret that is needed to work with an API.

Your example seems to suggest that, e.g., an API token, should be passed around in code, encrypted, and that a package key (generated with `secret_make_key()`) should be used to decrypt the token as needed. This package key, in turn, ought to be saved in `.Renviron` and retrieved with `Sys.getenv()` when needed. So my question is: why not save the API token in `.Renviron`, and read it directly from there? Are you purposely avoiding this approach for some security reason?

I had a look at packages listed as Reverse imports of `{httr2}`, and from source code inspection they all seem to read "secrets" needed to authenticate with APIs directly from the `.Renviron`.

So this makes me wonder the case where you would use `secret_encrypt()`, `secret_decrypt()` and `secret_make_key()` functions? Is it because you can have many secrets associated with an API, and that it would not be very practical to create environment variables for all those secrets, and therefore it is best to have them in my source code, encrypted, with the corresponding encryption key stored in `.Renviron`? Or is it somehow related to compliance with external workflows that need to access your secrets?

My question here also applies to your example of `get_api_key()` that handles the `{testthat`} context. Why, again, is in his example the testing key decrypted using `"HTTR2_KEY"`, while the `NYTIMES_KEY` is simply retrieved from the `.Renviron`? Why not retrieve both from `.Renviron`?

And, finally, when you suggest `set_api_key()` function for setting the API key, you mention that it is not good to encourage the user to type their secret into the console. But, then, why provide the example with the `key` argument? Why not simply...

```r
set_api_key <- function() {
  key <- askpass::askpass("Please enter your API key")
  Sys.setenv("NYTIMES_KEY" = key)
}
```

As a suggestion, and for someone who's just starting to deal with secrets and keys, it would be great to have an infographics depicting what is meant by package key, encryption key, secret and token, and the place in the filesystem relative to the package source where all this pieces of info should be.

All this being said, I really liked reading this vignette, and I think it is very clear.

Thanks in advance.

**Comment by hadley** [comment]
Thanks for the feedback! It'll probably be a while before I'm working on httr2 again, but I really appreciate all your comments.

I think one important distinction is that sometimes you have an app key that has to be bundled with the package, and sometimes each individual user has their own key. These need to be managed differently, and I've probably failed to explain the difference in the existing vignette.

**Comment by jennybc** [comment]
> why not save the API token in `.Renviron`, and read it directly from there?

Also, sometimes the "secret" is a whole credential object that cannot be stored as an environment variable. The sensitive item isn't necessarily a simple string, like an API key.

**Comment by jennybc** [comment]
Also you're bringing up a lot of questions I brought up in this PR / review, so that might be worth reading over. For example:

https://github.com/r-lib/httr2/pull/70#discussion_r709565220

**Comment by ramiromagno** [comment]
Thank you both for your prompt feedback!

As @hadley pointed out, I think, indeed, that I missed the point about the difference between the key bundled with the package, the developer's key (I assume), and other users' keys...

@jennybc : Thank you for your example of a secret other than a string, that helps understanding why you'd want to use encrypted secrets, indeed! And the comment in #70 discusses many of the doubts I was having.

**Comment by hadley** [comment]
@ramiromagno you're right — if you only have one secret there's no advantage to using the system described in the vignette, you can just store the secret directly in environment variables. The system is most useful when you have multiple secrets, or as @jennybc's says, when your secrets are simple strings. I've tried to make this a bit more clear in the vignette.
