### ISSUE TITLE
Document auth_params further

### ISSUE THREAD

**Issue by JosiahParry** [r-lib/httr2#117]
Upon reading documentation for `oauth_client()` it is unclear what the role of `auth_params` is or how to provide those values. The example excludes this argument. 

My present motivation for this issue is needing to specify `grant_type=client_credentials` in the body of the post request for the oauth token. 

https://github.com/r-lib/httr2/blob/87011c0ff31019409c4a5a700b041f279f054361/R/oauth-client.R#L32

**Comment by hadley** [comment]
Is there some reason you can't use `oauth_flow_client_credentials()` directly? Generally, you won't ever set the `grant_type` because it requires a bunch of implementation infrastructure to make that flow work.
