### ISSUE TITLE
Throttling

### ISSUE THREAD

**Issue by jennybc** [r-lib/httr2#12]
https://github.com/SerpentAI/requests-respectful

**Comment by hadley** [comment]
Discussing rate-limiting in #13

Could provide some throttling policy: 

```R
req_policy_throttle <- function(req, max_request, timespan, realm = req$url$hostname) {}
```

Would also make it easier to implement [polite](https://github.com/dmi3kno/polite).

**Comment by hadley** [comment]
Implemented in `req_throttle()`
