### ISSUE TITLE
Feature request: additional headers to the requests by oauth_client()

### ISSUE THREAD

**Issue by yutannihilation** [r-lib/httr2#122]
I wanted to try Twitter's API with OAuth2, but this code

``` r
client <- oauth_client(
  id = "<client ID>",
  secret = obfuscated("<obfuscated client secret>"),
  token_url = "https://api.twitter.com/2/oauth2/token",
  name = "rstats_ja_bot_test"
)

token <- oauth_flow_auth_code(client, 
  auth_url = "https://twitter.com/i/oauth2/authorize",
  scope = "tweet.read tweet.write offline.access",
  host_name = "127.0.0.1",
  port = 1410
)
```

ended up with this error:

```
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Error in `oauth_flow_abort()`:
! OAuth failure [unauthorized_client]
• Missing valid authorization header
```

After googling with the error message "Missing valid authorization header," I got to know that Twitter OAuth2 API requires a Basic authorization header for OAuth authorization.

https://twittercommunity.com/t/trying-to-get-oauth-2-0-token-receiving-missing-valid-authorization-header-error/163633/4

IIUC, httr2 doesn't provide the argument that the users can use to customize the requests like this. This case might be a rare one, but I'm wondering if there are more cases where the users need low level access.

**Comment by hadley** [comment]
Are you sure you can't put this in the `oauth_client()`'s `auth_param`s? I don't really remember how this code works but I do remember trying to make sure you could customise every part of the request.  If the customisation point doesn't already exist, I definitely want to add it.

**Comment by yutannihilation** [comment]
Hmm, I might be wrong..., but I couldn't find where `auth_params` is used when I execute the code above.

`auth_params` is stored in the `client`,

https://github.com/r-lib/httr2/blob/87011c0ff31019409c4a5a700b041f279f054361/R/oauth-client.R#L78-L89

`oauth_flow_auth_code()` calls `oauth_client_get_token()`

https://github.com/r-lib/httr2/blob/87011c0ff31019409c4a5a700b041f279f054361/R/oauth-flow-auth-code.R#L173

and then `client` is used in `oauth_client_req_auth()`, which actually calls `oauth_client_req_auth_body()`, but it seems this function doesn't use `auth_params. 

https://github.com/r-lib/httr2/blob/87011c0ff31019409c4a5a700b041f279f054361/R/oauth-client.R#L230
https://github.com/r-lib/httr2/blob/87011c0ff31019409c4a5a700b041f279f054361/R/oauth-client.R#L182-L188

**Comment by hadley** [comment]
Oh good point. So maybe that's the wrong path way and `req_flow_auth_code` needs a `token_headers` argument or similar?

**Comment by hadley** [comment]
Can you help me make a reprex? I have a native app with OAuth 2.0 enabled, but when I run the code above I see

<img width="532" alt="Screen Shot 2022-04-26 at 15 41 33" src="https://user-images.githubusercontent.com/4196/165388746-debb2390-74f6-4abc-ae96-f311df5385c0.png">

**Comment by hadley** [comment]
Maybe you're using a confidential app, since you included the secret in your example?

**Comment by hadley** [comment]
Reading my docs suggests that maybe you need

```R
client <- oauth_client(
  id = "<client ID>",
  secret = obfuscated("<obfuscated client secret>"),
  token_url = "https://api.twitter.com/2/oauth2/token",
  name = "rstats_ja_bot_test", 
  auth = "header"
)
```

That should generate the basic auth header for you.

**Comment by yutannihilation** [comment]
Sorry, I forgot everything about OAuth, so I might be terribly wrong... I didn't respond because I saw several other errors even if I succeed to get token with some tweaks. I'll try it, thanks!

**Comment by hadley** [comment]
@yutannihilation no need to apologise because I have also forgotten everything about OAuth :smile: I'll keep trying.

**Comment by yutannihilation** [comment]
Yeah, OAuth is hard... Thanks.

IIRC, "Something went wrong" is what I saw when I set the callback URL as "http://127.0.0.1:1410" (without the tailing `/`). Here's my app setting, in case this is useful.

<details>

![image](https://user-images.githubusercontent.com/1978793/165520794-cee08123-f1ba-42db-b924-2c96353e06fb.png)

</details>

**Comment by yutannihilation** [comment]
You are right, adding `auth = "header"` solved all the problems. Sorry that I didn't read the document enough... I'm still not sure if I understand OAuth enough, but, as I don't see anything that should be addressed on httr2's side, I'm closing this issue. Thanks so much for your help!

**Comment by hadley** [comment]
Ok, great, I'm glad httr2 already had what you needed 😁
