### ISSUE TITLE
url_parse() incorrectly parses URLs without a scheme

### ISSUE THREAD

**Issue by allenbaron** [r-lib/httr2#127]
The hostname of URLs without a scheme are incorrectly parsed as the path by `httr2::url_parse` (the same is true for `httr::parse_url`).

``` r
library(httr2)

url_parse("google.com")
#> <httr2_url> google.com
#> • path: google.com
```
<sup>Created on 2022-04-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

## Resulting Problems

1. requests using `req_throttle()` with these URLs when `realm` is not specified will fail, even though the request itself would succeed.

``` r
library(httr2)

r <- request("google.com")

r %>%
    req_throttle(rate = 1) %>% 
    req_perform()
#> Error in the$throttle[[realm]]: attempt to select less than one element in get1index

req_perform(r)
#> <httr2_response>
#> GET http://www.google.com/
#> Status: 200 OK
#> Content-Type: text/html
#> Body: In memory (15975 bytes)

r %>%
    req_throttle(rate = 1, realm = "google.com") %>%
    req_perform()
#> <httr2_response>
#> GET http://www.google.com/
#> Status: 200 OK
#> Content-Type: text/html
#> Body: In memory (15959 bytes)
```
<sup>Created on 2022-04-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

2. Response URLs might not be parseable.
This may be a rare corner case but a similar problem has been documented in httr (https://github.com/r-lib/httr/issues/607).

``` r
library(httr2)

r <- request("rarediseases.org/robots.txt")
x <- req_perform(r)

x$url
#> [1] "rarediseases.org/robots.txt"

url_parse(x$url)
#> <httr2_url> rarediseases.org/robots.txt
#> • path: rarediseases.org/robots.txt
```
<sup>Created on 2022-04-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by hadley** [comment]
Hmmmm, it is parsing that url correctly because it omits a scheme. I think it would be a better to cleanly error when no scheme is provided.

Or maybe it would be better to switch to curl's url parser: https://github.com/jeroen/curl/issues/266

**Comment by hadley** [comment]
@hongooi73 I think the main problems is that the parser is clearly different to curl's, since `req_perform(request("google.com"))` works.

**Comment by hadley** [comment]
I don't think there's currently much we can do here, except recommend that you provide a fully formed url. Otherwise, I think a proper fix would requiring reading and recreating curl's parsing code, which seems unlikely to be worth the effort.
