### ISSUE TITLE
Why not automatically set `cookie = "_nss=1"`?

### ISSUE THREAD

**Issue by jchrom** [r-lib/httr2#140]
More of a question than a bug report. 

When I was trying to figure out why my redirects work with `httr` but not with `httr2`, I saw that `httr::POST()` includes `_nss=1` by default. It would appear that at least some servers won't include location header on redirect, unless this cookie is present. For `httr2`, calling `httr2::req_options(req, cookie = "_nss=1")` resolves the problem.

I don't now how this is implemented in `httr`, but since the behaviour is different from `httr2`, I thought I would point it out and ask whether it is something we want to replicate in `httr2`.

**Comment by hadley** [comment]
Googling suggests that `_nss` isn't a common standard. So this might be a consequence of httr's handle pool that preserves cookies across requests.

**Comment by jl5000** [comment]
Does that mean the httr2 doesn't preserve cookies across requests? It would explain the issues I'm having and that I've seen one or two on Twitter having too.

**Comment by hadley** [comment]
Yeah. Now tracking in #223
