### ISSUE TITLE
Default resp value for resp_body_* functions

### ISSUE THREAD

**Issue by samterfa** [r-lib/httr2#143]
I'm really enjoying this package, thank you!

I imagine there's a good reason this is not the case, but could the default value for the resp parameter in the resp_body_* or even all resp_* functions be last_response()? The documentation does say that last_response() is for debugging so maybe it shouldn't be relied upon, but it's super handy.

Thanks!

**Comment by hadley** [comment]
Hmmmm, I think I'd prefer to keep this explicit. You really should be deliberately capturing the response, not relying on some global state.
