### ISSUE TITLE
More glue-like behavior for `req_template()`

### ISSUE THREAD

**Issue by nbenn** [r-lib/httr2#144]
I was surprised to see the following behavior. While everything works nicely in the first example, things fall apart as soon as eval is required. Of course, this can easily be avoided, I just thought I'd point it out as it caught me off guard, given the glue-like syntax.

```r
library(httr2)

req <- request("http://httpbin.org/cookies")

name <- "id"
value <- "a3fWa"

req_template(req, "GET /set/{name}/{value}")
#> <httr2_request>
#> GET http://httpbin.org/cookies/set/id/a3fWa
#> Body: empty

lst <- list(name = "id")
fun <- function() "a3fWa"

req_template(req, "GET /set/{lst$name}/{lst$value}")
#> <httr2_request>
#> GET http://httpbin.org/cookies/set/{lst$name}/{fun()}
#> Body: empty
```

**Comment by hadley** [comment]
It might look glue-like, but it comes from a very different place. I don't think the intent is to support general glue like interpolation.
