### ISSUE TITLE
Handle Maximum POST size automatically (or perhaps with some helper function)

### ISSUE THREAD

**Issue by ramiromagno** [r-lib/httr2#146]
Hi httr2 team,

Can httr2 somehow handle a Maximum POST size? I mean, if the message to be sent by POST exceeds a maximum length then it is split automatically by httr2 that then would automatically perform the various requests and assemble the responses into one...

Here is an example that imposes a maximum length of 50: https://rest.ensembl.org/documentation/info/sequence_id_post.

Perhaps related to this othe discussion: https://github.com/r-lib/httr2/issues/8.

**Comment by hadley** [comment]
Is this an HTTP standard thing? If not, it’s likely out of scope for httr2.

**Comment by ramiromagno** [comment]
I honestly don't know if it's standard. Just thought it would be nice to have it.

I got the impression that if you tackled the pagination problem (https://github.com/r-lib/httr2/issues/8), and return a list of responses for the user to handle, then this would be similarly addressable.

**Comment by hadley** [comment]
I haven't seen it before, which suggests it's not a terribly common need, which implies it's out of scope for httr2 too, sorry.
