### ISSUE TITLE
Equivalent of `fetch_token` with `auth_code`

### ISSUE THREAD

**Issue by vanhry** [r-lib/httr2#151]
Hello everyone!
I want to replicate **python** example of receiving both access and refresh tokens, like here **(Python)**
```python
token_response = oauth2_session.fetch_token(TOKEN_GRANT_URL, code=AUTHORIZATION_CODE, client_secret=CLIENT_SECRET)
```
How could I do it using `httr2` library?

There are my previous steps to get the `AUTHORIZATION_CODE` **(R)**
```R
client <- httr2::oauth_client(token_url = token_grant_url,secret = .app_secret,id = .app_key)
url_to_browse <- httr2::oauth_flow_auth_code_url(client=client, auth_url = auth_url,
                                                 scope = paste0(SCOPES_TO_REQUEST, collapse = " "),
                                                 redirect_uri = .client_redirect,state = STATE)

```
But I don't understand which function should I use instead of `fetch_token`
Thanks for any help you can provide

**Comment by hadley** [comment]
I don't know what `fetch_token` does, so unfortunately I can't help.
