### ISSUE TITLE
`oauth_client_get_token` uses default User Agent

### ISSUE THREAD

**Issue by jl5000** [r-lib/httr2#155]
I'm seeing that when a client is registered it seemed to be using the default user agent string instead of the custom one I had defined. I think I've traced it back to the `oauth_client_get_token()` function which posts data to the `token_url` without using the same User Agent string.

**Comment by hadley** [comment]
Could you provide a simple reprex? Just so I get a sense of what you're doing.

**Comment by jl5000** [comment]
I'd be happy to but there are two blockers which I can't see a way around:

1.  The function does not take the user agent as an argument
2.  The function creates a request and processes the response in one go

**Comment by hadley** [comment]
In that case, could you do a PR?

**Comment by hadley** [comment]
Closing since I don't understand what you want 😄
