### ISSUE TITLE
possibly add a function to modify curl handle options

### ISSUE THREAD

**Issue by fangzhou-xie** [r-lib/httr2#160]
First of all, thanks for this package! 

I wonder if it is possible to have a function to control curl handle options? I noticed that [`req_perform` function](https://github.com/r-lib/httr2/blob/main/R/req-perform.R#L294) will eventually set the handle options using the `req$options` but there are only several items can be modified by the existing functions (useragent, proxy, etc). If, for example, I want to set the `maxage_conn` option, I have to do:

```
req <- request("https://example.com") %>% 
  req_proxy("127.0.0.1", 1234) %>% 
  req_user_agent("something here")
req$options$maxage_conn <- 10
```

I was thinking if it is better to have a similar `httr2-style` function, say `req_curl_options = function(.req, ...)`, to directly modify the content of the request options? Thus, the request can be chained in the usual way:

```
req <- request("https://example.com") %>% 
  req_proxy("127.0.0.1", 1234) %>% 
  req_user_agent("something here") %>% 
  req_curl_options(maxage_conn = 10) # not implemented, just concept
```

**Comment by hadley** [comment]
Yeah, thats a good idea.

**Comment by fangzhou-xie** [comment]
Thanks! Actually I found the existing function [`req_options`](https://github.com/r-lib/httr2/blob/main/R/req-options.R#L21) , which does exactly what I described above. Sorry for the duplication. 

But somehow this function is not shown on the [pkgdown website](https://httr2.r-lib.org/reference/index.html). I did also find the corresponding html file generated in the [gh-pages branch](https://github.com/r-lib/httr2/blob/gh-pages/reference/req_options.html) though.

**Comment by hadley** [comment]
Yeah, good idea. I thought it must exist too but didn't see it on the website 😬
