### ISSUE TITLE
Release date of httr2 v0.2.2

### ISSUE THREAD

**Issue by wing328** [r-lib/httr2#167]
Hi team,

Thanks for the great work on httr2. Recently we add `httr2` library support to the R client generator in the [OpenAPI Generator](http://github.com/openapitools/openapi-generator) project and some users definitely prefer httr2 over httr that we originally support.

May I know what's the release date of the upcoming version v0.2.2?

We're particularly interested in this fix: https://github.com/r-lib/httr2/pull/153, and we're asking our users to install httr2 latest master for the time being.

Thank you.

William

**Comment by hadley** [comment]
Given #166, probably next week.
