### ISSUE TITLE
Should we provide generic oob for `req_oauth_auth_code()`?

### ISSUE THREAD

**Issue by hadley** [r-lib/httr2#176]
Like gargle is doing to work around Google's deprecation of `oob`.

Should include instructions on how to publish to your own server: https://github.com/r-lib/gargle/blob/main/inst/pseudo-oob/google-callback/index.html

Also needs tweaks to `oauth_auth_code()` to opt-out of local server. Would be useful to apply some heuristics to figure out when you need the OOB flow (which gargle likely has).

**Comment by JosiahParry** [comment]
Commenting for support of oob in httr2. Though it isn't too difficult to fake it with what is already available. 

related to https://github.com/r-lib/httr/issues/617


```r
  client <- oauth_client(...)

  auth_url <- oauth_flow_auth_code_url(client, auth_url = ".../authorize", redirect_uri = "urn:ietf:wg:oauth:2.0:oob")
  
  browseURL(auth_url)
    cli::cli_alert_info("Paste authorization code:")
    token <- readline()
```
