### ISSUE TITLE
OAuth caching does not respect `refresh_token`

### ISSUE THREAD

**Issue by mgirlich** [r-lib/httr2#178]
The caching does not respect the refresh token.

``` r
library(httr2)

client <- oauth_client("example", "https://example.com/get_token")
req <- request("https://example.com")

# create 2 requests with different refresh token
req1 <- req %>% 
  req_oauth_refresh(client, refresh_token = "rt1")
req2 <- req %>% 
  req_oauth_refresh(client, refresh_token = "rt2")

# simulate that we made a request and got back a token
token <- oauth_token(
  access_token = "a",
  token_type = "bearer",
  expires_in = NULL,
  refresh_token = "rt1",
  .date = Sys.time()
)
# ... that is now cached
req1$policies$auth_oauth$cache$set(token)
req1$policies$auth_oauth$cache$get() %>% str()
#> List of 3
#>  $ token_type   : chr "bearer"
#>  $ access_token : chr "a"
#>  $ refresh_token: chr "rt1"
#>  - attr(*, "class")= chr "httr2_token"
# but also in req2
req2$policies$auth_oauth$cache$get() %>% str()
#> List of 3
#>  $ token_type   : chr "bearer"
#>  $ access_token : chr "a"
#>  $ refresh_token: chr "rt1"
#>  - attr(*, "class")= chr "httr2_token"

# or shown in `auth_oauth_sign()` which is used in `req_perform()`
req1 %>% 
  httr2:::auth_oauth_sign() %>% 
  print(redact_headers = FALSE)
#> <httr2_request>
#> GET https://example.com
#> Headers:
#> • Authorization: 'Bearer a'
#> Body: empty
#> Policies:
#> • auth_oauth: a list

req2 %>% 
  httr2:::auth_oauth_sign() %>% 
  print(redact_headers = FALSE)
#> <httr2_request>
#> GET https://example.com
#> Headers:
#> • Authorization: 'Bearer a'
#> Body: empty
#> Policies:
#> • auth_oauth: a list
```

<sup>Created on 2022-10-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by jennybc** [comment]
@mgirlich Can you give more context for this? I'd just be interested to learn of the real-world situation where you bumped your shins on this.

Wearing my gargle hat, this feels related to why gargle built on top of httr's cache key, by also respecting the user's email address, i.e. that was my motivation for using more info in the cache look-up.

I can't really see why one would want two refresh tokens that are essentially the same in terms of what they can accomplish. But that is likely just a lack of imagination, hence my question. Does this have anything to with scopes?

**Comment by mgirlich** [comment]
I bumped into this because we manage multiple different user accounts. That is, you don't only need to connect to your own account but to many different ones. This can be a common use case where BI systems come into play.
So, the scopes don't matter but the different refresh token simply stands for different accounts.

**Comment by mgirlich** [comment]
Isn't that exactly what I did in my PR #179? The issue is that it explicitly used `cache <- cache_mem(client, NULL)` (so no cache key) and I changed it to `cache <- cache_mem(client, refresh_token)`.
