### ISSUE TITLE
Trouble using streaming data and WebSocket with httr2

### ISSUE THREAD

**Issue by lassehjorthmadsen** [r-lib/httr2#181]
I'm writing a API wrapper package using `httr2` and have an issue with streaming data. I'm not sure if this is a bug or the functionality is just not covered by `httr2`.

My use case is to get stock prices from a streaming endpoint, using the common workflow of creating a subscriprtion, then receiving streams of data from that subscription. 

My provider is [Saxo Bank](https://www.developer.saxo/openapi/learn), their API documentation for streams is [here](https://www.developer.saxo/openapi/learn/streaming), whith [this](https://www.developer.saxo/openapi/learn/streaming#:~:text=let%20us%20know.-,Connecting%20to%20the%20WebSocket%20server,-To%20connect%20to) section being the most relevant. 

The idea is to send a GET request to an endpoint, including a `contextId`. With headers `Connection: Upgrade` and `Upgrade: WebSocket`, the connection upgrades to the WebSocket protocol, `wss://`. However, I don't seem to recieve any streaming data, and I can't figure out if it is because WebSocket is not supported, if there's a bug, or if I'm doing something wrong. Below is a code snippet to show what I'm doing. 

Any help much appreciated. 

Code:

```
# Try handling streaming responses from Saxo with httr2

library(tidyverse)
library(httr2)

# 24 hour token for simulation environment
token24  <- "BEARER [TOKEN]"

# Create subscription for a specific stock
req <-
  request("https://gateway.saxobank.com/sim/openapi/trade/v1/prices/subscriptions") %>%
  req_body_json(data = list(
    "Arguments" =
      list("Uic" = 15611,
           "AssetType" = "Stock"),
    "ContextId" = "aUv1j3U-Or3", # Arbitrary string, for identification
    "ReferenceId" = "5MolAro8Zz")) %>%
  req_headers(Authorization = token24)

resp_status_desc(r) # "Created" -- works nicely so far

# Streaming responses
# First, a call-back function
write_stream <- function(x) {
  x %>% write_file("data-raw/temp", append = TRUE)
  TRUE
}

# Make GET request, as explained here:
# https://www.developer.saxo/openapi/learn/streaming#:~:text=let%20us%20know.-,Connecting%20to%20the%20WebSocket%20server,-To%20connect%20to

req <- request("https://streaming.saxobank.com/sim/openapi/streamingws/connect") %>%
  req_url_query(`contextId`= "aUv1j3U-Or3") %>%
  req_headers(Authorization = token24,
              Connection = "Upgrade",
              Upgrade = "Websocket",
              `Sec-WebSocket-Key` = "SGVsbG8sIHdvcmxkIQ==",
              `Sec-WebSocket-Version` = 13)

req %>% req_stream(write_stream) # Nothing happens
```

**Comment by lassehjorthmadsen** [comment]
Thanks, @hadley, I tried the websocket package, but so far without luck. That package lets you send a request via the wss protocol, but it seems my provider really depend on authenticating and passing parameters via https while using headers `Connection: Upgrade` and `Upgrade: WebSocket`. The connection then "upgrades" to wss. But I can't go directly to wss it seems.

My impression is that the "upgrade from https to wss" approach is common in financial applications.

**Comment by hadley** [comment]
I'll keep an eye on this issue to see if it crops up for other people, otherwise I think this is unfortunately out of scope for httr2.
