### ISSUE TITLE
further clarify `paths` argument 

### ISSUE THREAD

**Issue by JosiahParry** [r-lib/httr2#184]
The `paths` argument _implies_ that the request bodies will be written to disk. 
After testing this on my own, it appears that the request body type is inferred and written accordingly.

https://github.com/r-lib/httr2/blob/d78544d633a874eac9efb44fbfde8bcded77b4f1/R/multi-req.R#L25

```r
library(httr2)

list(
  request("https://httpbin.org/image/jpeg"),
  request("https://httpbin.org/image/svg"),
  request("https://httpbin.org/bytes/200")
) |> 
  multi_req_perform(paste0("request", 1:3))
```

Perhaps the argument can be rewritten to be more informative.

**Comment by hadley** [comment]
What you mean by the type being inferred?

**Comment by JosiahParry** [comment]
It's likely that I just don't know how http requests work all that well. Perhaps "format" is a better word here. When running multi_req_perform() with paths set, I was unsure what format of file I was going to receive. With the above example, the files were written as a jpeg, svg, and binary respectively. Looking at this now,  the file type is based on the `Content-Type` header.  

<img width="340" alt="image" src="https://user-images.githubusercontent.com/13534508/206764458-ad033713-5ade-4690-868b-b288989d72a2.png">

**Comment by hadley** [comment]
`multi_req_perform()` just writes the raw bytes that it receives to disk so it doesn't concern itself at all with the type/format.
