### ISSUE TITLE
feature request: specify success handler for `multi_req_perform()`

### ISSUE THREAD

**Issue by JosiahParry** [r-lib/httr2#185]
Feature request: like `req_stream()` has a call back function that allows us to specify how the the result is handled, it would be very nice if users had the option to handle request body on success by specifying a function. Or, at minimum specify the response type e.g. with `resp_body_string()` or `resp_body_raw()`

https://github.com/r-lib/httr2/blob/87011c0ff31019409c4a5a700b041f279f054361/R/multi-req.R#L138

**Comment by hadley** [comment]
What would you use it for? I don't get the benefit of registering a callback when you already get a data frame with all the responses.

**Comment by JosiahParry** [comment]
I would use it to process the request. As I understand it, `multi_req_perform()` performs the requests in parallel. It would be great to be able to process the requests in the multiple threads prior to having them collected. That way one would not be required to iterate over the result using say `lapply()` or `purrr::map()` in a single thread afterwards. I suspect that being able to utilize the threads would be an overall faster experience.

**Comment by hadley** [comment]
The threads are provided by curl so the only thing we can do in them is download.
