### ISSUE TITLE
Check whether caching is correct in `req_oauth_client_credentials()` and `req_oauth_bearer_jwt()`

### ISSUE THREAD

**Issue by mgirlich** [r-lib/httr2#192]
Similar to #178 where the caching didn't respect when the refresh token changed (e.g. in the context of supporting multiple accounts from the same client). See #179 what was done so far for the refresh token case.

**Comment by hadley** [comment]
`req_oauth_client_credentials()` doesn't need it because their auth is explicitly bound to the client.

`req_oauth_bearer_jwt()` should include the claim in the cache key.
