### ISSUE TITLE
Handling "connection refused" error

### ISSUE THREAD

**Issue by ErdaradunGaztea** [r-lib/httr2#194]
I'm implementing a Shiny app and use {httr2} to handle API requests. `req_error()` and `resp_is_error()` work great to cover 4xx and 5xx status codes, but I suspect that the API might be down sometimes and I'd get "Connection refused" error. I'd like to capture this case as well and display an appropriate alert, but `req_error()` doesn't capture that (nor it should).

While I could use a `tryCatch()` strategy, it would be much more readable if a `req_refused() / req_disconnected() / etc.` was implemented to set capture strategy for cases like refused connection. I'm not sure how the workflow would look like given that no response is generated, though.

Perhaps a similar case would be an "unresolved host" error.

Oh, and an easy way to generate such "connection refused" error is to connect with localhost on some empty port, say:

```r
request("127.0.0.1:9183") %>%
  req_method("GET") %>%
  req_perform()
```

**Comment by hadley** [comment]
I think you do need to handle with a `tryCatch()`, but we could do a better job of documenting it.

**Comment by hadley** [comment]
Also, unless I'm interpreting the code incorrectly, `req_retry()` will still work with this sort of error.
