### ISSUE TITLE
Document error classes

### ISSUE THREAD

**Issue by mmuurr** [r-lib/httr2#195]
This might be a "won't do" (or even a "bad idea" :-), but I'm curious if there's appetite for `req_error()` to iteratively modify a request with error-handlers, rather than replacing only the last error-handler spec. For example:
```r
echo <- function(code) {
  url <- glue::glue("https://httpbin.org/status/{as.integer(code)}")
  request(url) |>
    req_error(
      is_error = function(resp) resp_status(resp) == 404,
      body = function(resp) "four zero four"
    ) |>
    req_error(
      is_error = function(resp) resp_status(resp) == 503,
      body = function(resp) "five zero three"
    ) |>
    req_perform() |>
    print()
}

echo(404)  ## uses standard error-handler
echo(503)  ## prints "five zero three" as part of the error message
echo(400)  ## uses standard error-handler
```

The first (404) handler is (silently) _replaced_ by the second (503) error-handler in the request-building chain. I ginned-up that experiment thinking that perhaps the handlers are added similarly to filters in {plumber} and other incremental Request-modifiers (`req_url_query()`, `req_headers()`, etc.). There's obviously room for debate as to what the desired behavior should be if the matching predicate would return `TRUE` for multiple handlers (take the first in the pipeline? the last? compose all the matching handlers?).

My curiosity is simply from the perspective of being able to incrementally add special error handlers (i.e. composing Request objects) using the syntax similar to the above as opposed to incrementally-building a single error-handler function that handles the conditional logic itself.

{httr2} is great, BTW, and I'm enjoying migrating some previous {httr} patterns to it :-)

**Comment by hadley** [comment]
Hmmmm, that's because `req_error()` is about handling errors not error handlers 😉. The overall goal is more about consistently handling all errors from an API in one swoop, than changing behaviour for different http error codes. Can you give a bit more context on the motivating problem?

**Comment by mmuurr** [comment]
Yeah I see your point -- it's a bit more about defining _what_ is an error at all (i.e. when to plumb into R's condition-signaling system).

I don't have an exact problem right now (the above was really just a curiosity, thinking forward), so I'm definitely speculating here, but consider a package/library the generates Requests, and the programmer does not have control of this package; instead, the programmer uses this package as part of a Shiny application.

The package may provide a Request-building function like so:
```r
gen_req <- function(client_id) {
  request(some_url_defined_elsewhere_in_the_package) |>
    req_error(body = function(resp) sprintf("client_id: %s", client_id))  ## some annotations to help with error-logging
}
```
The package author has implicitly decided that everything 400-and-up is an error and should signal.

The Shiny author now may want to use this Request object and do something special for 500-and-up errors (e.g. send an automated alert to someone). I think it's reasonable (though possibly faulty) to think they may try something like:
```r
thepkg::gen_req(some_client_id) |>
  req_error(
    is_error = \(resp) resp_status(resp) >= 500,
    body = \(resp) {
      send_alert_to_the_important_but_unfortunate_person_on_call(on_call_user_id)
      sprintf("alert sent to %s", on_call_user_id)
    }
  ) |>
  req_perform()
```
... which _will_ work, but now they've lost that useful `client_id` annotation on the 400-series errors that shipped with the package.

Obviously they could instead just swallow all errors with `req_error(~ FALSE)` and examine the response and handle them explicitly (with basic conditional logic on `resp_status()`), but again they lose some out-of-the-box functionality the package author provided.

I'm stretching a bit here, but I don't think it's **un**reasonable to assume somebody's tried something like that somewhere ;-)

BTW -- I've also considered handling errors like so:
```r
tryCatch({
  request(...) |>
    req_error(body = \(resp) "some useful annotation") |>
    req_perform()
}, httr2_http_404 = function(e) {
  ## handle 404
}, httr2_http_503 = function(e) {
  ## handle 503
}, error = function(e) {
  ## handle other errors
}
```
... as we can see the error condition classes {httr2} generates. But I don't see these classes described officially in documentation anywhere, so I assume such a pattern is a bit risky (and minimally officially unsupported)?

In any case, nothing major here, just thinking aloud through some decent/extensible error-handling frameworks :-)

Thanks again for {httr2}!

**Comment by hadley** [comment]
Thanks for the explanation!

Yeah, I think the `tryCatch()` pattern is better here. You can consider those class to be part of the public API and rely on them, and we should document them so that's obvious.
