### ISSUE TITLE
Feature request: export (and factor) `resp_abort()` functionality

### ISSUE THREAD

**Issue by mmuurr** [r-lib/httr2#196]
Currently `resp_abort()` is non-exported. It's nice to be able to use a consistent {httr2} codepath to possibly create new conditions, however. For example, we may want to signal on a 3xx error. Or, alternatively, we may want to capture a 4xx error, inspect the error reason, _alter the condition object_ and re-throw.

An example of that second use case is with some AWS APIs, where all 4xx errors are rolled into a single `400` response with the actual error reasons sent along in the response body. The [AWS Cognito Token endpoint](https://docs.aws.amazon.com/cognito/latest/developerguide/token-endpoint.html) is one such example. That endpoint can _also_ send 5xx errors back (which we'd like to signal as an error as usual), but we may take differential action depending on whether or not the underlying `400` error reason is "invalid_client". We might want to add an `invalid_client_error` class to the {httr2} 'standard' condition object, e.g., for easier handling by a function-caller upstream.

Detecting that situation might look like:
```r
tryCatch({
  resp <- req |> req_perform()
  ## handle non-error normally
}, httr2_http_400 = function(e) {
  reason <- attr(e, "resp") |> resp_body_string() |> parse_error_reason()
  if (identical(reason, "invalid_client")) {
    stop(structure(e, class = c("invalid_client_error", class(e))))  ## or perhaps rlang::cnd_signal()
  } else {
    stop(e)  ## re-throw; or perhaps rlang::cnd_signal()
  }
})
```
... which has that somewhat ugly `attr(e, "resp")` portion.

Another approach might be:
```r
resp <- req |> req_error(\(x) FALSE) |> req_perform()
if (resp_status(resp) == 400L) {
  reason <- resp |> resp_body_string() |> parse_error_reason()
  if (identical(reason, "invalid_client")) {
    ## now I want to 're-throw' what _would_ be the normal httr2 condition, but with a class added.
    ## instead, I need to do something like:
    cnd <- tryCatch(httr2:::resp_abort(resp), error = identity)  ## purposefully throw-and-catch just to get the condition :-|
    stop(structure(cnd, class = c("invalid_client_error", class(cnd))))
  } else {
    httr2:::resp_abort(resp)
  }
} else if (resp_status(resp) > 400L) {
  httr2:::resp_abort(resp)
} else {
  ## handle non-error normally
}
```
Both of these feel kinda clunky and I'd rather just be able to promote _any_ {httr2} response I want into a condition using something similar to:
```r
resp_cnd <- function(resp, type = c("error", "warning", "message"), cls = character(0), info = NULL) {
  ## builds a condition similarly to the current httr2::resp_abort,
  ## but who's class is `c(cls, "httr2_http_<status>", "httr2_http", "rlang_<type>", "<type>", "condition")`
}
```

Another advantage to such a condition-builder is the ability to more easily construct conditions for, say, 3xx-responses, on which we may want to raise warnings. (Unexpected redirects warrant warnings :-) Again, this is detectable and doable without exporting {httr2} condition-building, but the workarounds feel ... ugly(?), and there's some niceness to having a single consistent mechanism in place to create {httr2} condition objects that always have, e.g., the "resp" attribute set, along with the canonical `httr2_http_<status_code>` class.

Again, it goes without saying (though I'll say it anyway), this is only a polite thought-experiment veiling as a feature request, and if this is outside the scope of {httr2} I totally get it ... thanks again for the work and consideration in either outcome!

**Comment by hadley** [comment]
Hmmm, I think I'd write something like this:

```R
withCallingHanders(
  resp <- req |> req_perform(),
  httr2_http_400 = function(e) {
    reason <- attr(e, "resp") |> resp_body_string() |> parse_error_reason()
    if (identical(reason, "invalid_client")) {
      abort(class = "invalid_client_error", parent = e)
    }
  }
)
```

That does lose the httr2 class on the error, but I _think_ that makes sense since it's no longer httr2 throwing the error?

**Comment by mmuurr** [comment]
Ah, I'm probably not familiar enough with the 'parent' notion of conditions to have thought of that initially.

In my original line of thinking I liked still having `httr2_http` be one of the classes so that the upstream caller can deal with all HTTP errors generically (if so desired). Re-reading my initial post I don't think I was perfectly clear, either ... ultimately the scenario that got me down this path was wanting to conceptually 'inherit' from a `httr2_http_400` error in an OOP sense, but perhaps the 'parent' construct helps with this. I'll think about this some more and follow-up!

**Comment by hadley** [comment]
In the AWS context, being able to extend httr2 errors does make a lot of sense. However, I don't think there's much precedence, so it's hard to know how useful it will be and what infrastructure it needs. Still, it might be an interesting/worthwhile experiment to perform. 

I think usage would probably look something like this:

```R
withCallingHandlers({
  resp <- req |> req_perform()
}, httr2_http_400 = function(e) {
  reason <- attr(e, "resp") |> resp_body_string() |> parse_error_reason()
  if (identical(reason, "invalid_client")) {
    resp_abort(resp, class = "invalid_client_error")
  }
})
```

(But I have a vague recollection that doesn't "eat" the original httr2 error so you get two errors emitted)

A couple of other possible routes:

* Expose more options in `resp_error()`, but that seems like it will need a lot of arguments if you also wanted to be able to optionally generate warnings.
* Add more powers to `resp_check_status()`

**Comment by hadley** [comment]
I've thought about this a bit, and overall it doesn't feel like quite the right time to export `resp_abort()` given that we've never really thought about how to subclass errors in this way. I think what you want makes sense, but I'm just concerned about the long term consequences of making a bad design decision here.
