### ISSUE TITLE
Diferent refresh token in each oauth refresh

### ISSUE THREAD

**Issue by llrs** [r-lib/httr2#197]
In #122 it was mentioned how to set the token with an access and a refresh token in the Twitter API.

httr2 has a `oauth_flow_refresh` (which is not in the reference page in the website) to refresh an access token if needed has expired. It checks that the new refresh token is the same as the previous one. However, Twitter doesn't use the same refresh token always, each time [the refresh token changes](https://twittercommunity.com/t/unable-to-obtain-new-access-token-by-using-refresh-token/164123/16). This is related to #186 if not the same issue.

Using `oauth_flow_refresh` expires the current token because the refresh token is used but an error is triggered without returning the new token. 

I would suggest a new parameter `strict = TRUE` to control if the check of the new refresh token is different from the old one. This would be backwards compatible and would work in this scenario by setting a `strict = FALSE`.

**Comment by hadley** [comment]
You shouldn't generally need to use `oauth_flow_refresh()` to refresh a token; if you're set up correctly, httr2 will refresh for you. More discussion in #186.
