### ISSUE TITLE
Passing query parameters as a list?

### ISSUE THREAD

**Issue by maelle** [r-lib/httr2#201]
I have query parameters for a request as a named list. 

It seems that at the moment it can't be passed directly to `httr2::req_url_query()`, so I do something like:

```r
args[[".req"]] <- req_without_query
req <- do.call(what = httr2::req_url_query, args = args)
```

which works but seems inelegant. Is there a better way with httr2? Could there be? Or should I refactor my own code? :smile_cat: 

Cc @dpprdan

**Comment by jchrom** [comment]
In case it is relevant: If you only need to pass the query parameters in a list, and not the request object itself, this works well for me:

```
httr2::req_url_query(req, !!!my_named_list)
```

**Comment by maelle** [comment]
thank you @jchrom!!

**Comment by maelle** [comment]
then my feature request is probably just an example in the docs :sweat_smile:
