### ISSUE TITLE
Vectorise functions

### ISSUE THREAD

**Issue by multimeric** [r-lib/httr2#209]
It would be ideal if `httr2` could handle a vector of URLs, for example to mutate a vector of URLs in a data frame to the data they point to. I realise this would require some changes to the subsequent pipeline functions. Currently this happens:

```R
> httr2::request(c("https://r-project.org", "https://httr2.r-lib.org/"))
Error in `new_request()`:
! `url` must be a string
Run `rlang::last_error()` to see where the error occurred.
```

**Comment by hadley** [comment]
I don't think this is a good approach for httr2, since in general, many things can vary between requests, not just urls.
