### ISSUE TITLE
Expand on caching in Wrapping APIs

### ISSUE THREAD

**Issue by JosiahParry** [r-lib/httr2#210]
The Wrapping API's article mentions that oauth2 tokens are automatically cached so that they can be reused automatically throughout the session. 

Ask: Can the article or the `req_perform()` documentation be enhanced so users understand how to take advanced of this feature? 

https://github.com/r-lib/httr2/blob/2584361c1853e2ecf4d1728f80def74c351b1b59/vignettes/articles/wrapping-apis.Rmd#L872

This seems like a great feature. I am unclear how to utilize this caching, though. `req_perform()` documentation states 

> If you are using OAuth, and the cached token has expired, req_perform() will get a new token either using the refresh token (if available) or by running the OAuth flow.

Awesome! But It's unclear to me where that token is passed in or how its being fetched.

At present I'm taking the `httr2_token` object, extracting the `access_token` and manually passing it into a request. Based on these hints in the documentation I could be taking better advantage of httr2.

**Comment by hadley** [comment]
You shouldn't need to do anything: httr2 will cache for you in memory by default, and you can cache on disk by setting `cache_disk = TRUE`.

**Comment by JosiahParry** [comment]
It is still unclear of how to take advantage of the cached httr2_token object. 

Say I perform the oauth2 flow, how do subsequent calls that require a token know to grab the cached token and how to use it? Is this documented elsewhere?

**Comment by hadley** [comment]
Are you seeing repeated requests to re-auth through out the session? If not, caching is already working. But maybe you need to share a small reprex so I can understand what you’re doing?

**Comment by JosiahParry** [comment]
Thanks for the follow up! 

Here's a reprex for what I'm doing presently. Its based on the example from `?oauth_flow_auth_code`.

The API I'm using performs Oauth2 authorization. It then requires that the token be appended to the `?token` parameter in the url. I use `req_url_query()` to inject the `access_token` field from the `httr2_token` object. I do this for all requests. 

Is there a way that this can be avoided/improved using the caching? At this point, I don't see how httr2 benefits from the caching of the token.

```r
library(httr2)

client <- oauth_client(
  id = "28acfec0674bb3da9f38",
  secret = obfuscated(paste0(
    "J9iiGmyelHltyxqrHXW41ZZPZamyUNxSX1_uKnv",
    "PeinhhxET_7FfUs2X0LLKotXY2bpgOMoHRCo"
  )),
  token_url = "https://github.com/login/oauth/access_token",
  name = "hadley-oauth-test"
)

token <- oauth_flow_auth_code(
  client, 
  auth_url = "https://github.com/login/oauth/authorize"
)

request("https://httpbin.org/anything") |> 
  req_url_query(token = token[["access_token"]]) |> 
  req_perform()
```

**Comment by hadley** [comment]
Why are you not doing this?

```R
request("https://httpbin.org/anything") |> 
  req_oauth_auth_code(client,  auth_url = "https://github.com/login/oauth/authorize") |> 
  req_perform()
```
