### ISSUE TITLE
Suggests are not checked before use in examples, tests and vignettes

### ISSUE THREAD

**Issue by Enchufa2** [r-lib/httr2#211]
We found several issues when trying to package httr2 for Fedora. Essentially, the package cannot be checked without Suggests and `_R_CHECK_FORCE_SUGGESTS_=0`, so it would be nice, and would make our life easier, to throw some `skip_if_not_installed` in tests as well as `requireNamespace` checks in examples (particularly for `docopt`).

Additionally, there's a test and a vignette that require Internet access, which is something that isn't allowed in distribution builders, so it would help also to check first (e.g. with `curl::has_internet()`) and conditionalize the subsequent code based on that.

**Comment by hadley** [comment]
This is our standard policy: https://r-pkgs.org/dependencies-in-practice.html#sec-dependencies-in-suggests-in-tests. We're happy to accept PRs that add appropriate skips (as long as they're not too invasive) but we don't have plans to change our general process.

Similarly, we'd be happy to accept a PR that skips code that requires internet access.

**Comment by Enchufa2** [comment]
As for Suggests, the CRAN Repository Policy specifies:

> A package listed in ‘Suggests’ or ‘Enhances’ should be used conditionally in examples or tests if it cannot straightforwardly be installed on the major R platforms. (‘Writing R Extensions’ recommends that they are always used conditionally.)

Which leaves certainly a hole, and in practice it's not enforced. It saddens me that this has become standard policy in r-lib packages, because it makes the life of downstream packagers harder, not easier. :(

Regarding Internet access:

> Packages which use Internet resources should fail gracefully with an informative message if the resource is not available or has changed (and not give a check warning nor error).

Here the policy is pretty clear.

**Comment by hadley** [comment]
We attempt to follow the spirit of the CRAN policies, not the letter of them, and our policies work well for us across a very large number of packages.

**Comment by Enchufa2** [comment]
I understand your position, and I only ask for a little understanding in return for Linux distro maintainers. :)

I'm just trying to set a common ground for collaboration, because I'm always happy to contribute, and you say that you are happy to accept PRs for the issues reported, but at the same time, if these things are _not_ considered a bug from your side, then I have absolutely no incentives to collaborate, because I have no assurances that my contributions won't be dropped tomorrow, or e.g. a similar Internet access will be added somewhere else in the package.

So please let me know if you could give me some assurances that I won't be chasing my own tail here, or otherwise feel free to close this issue, and I'll understand that there are no such assurances and I'll thank you for your time.

**Comment by hadley** [comment]
If you add them, we'll keep them (we accept similar PRs from google folks for their special deployment needs). But given that we have no testing infrastructure to ensure that we correctly catch all suggested dependencies (and we're not currently interested in adding it), there's no guarantees we'll remember to add them for new code.

**Comment by Enchufa2** [comment]
Thanks, I'll look into it.

**Comment by hadley** [comment]
We're happy to work with you on this, I just don't want to over promise anything.
