### ISSUE TITLE
httr2 & req_proxy vs RCurl behaviour difference

### ISSUE THREAD

**Issue by yogesh-bansal** [r-lib/httr2#217]
I am trying to use a proxy server using the req_proxy function in a GET call, The proxy server is setup rotate IPs with each call but IPs are sticking with GET & req_proxy while it is working fine with RCurl and system curl commands.
I am unable to make sense of why the two are behaving differently.

````
> ## usname <- "username"
> ## uspwd <- "password"
> 
> ## Ip Sticking
> library(httr2)
> library(jsonlite)
> for(idx in 1:3)
+ {
+ 	req <- request("https://ipinfo.io")
+ 	req <- req %>% req_headers("Accept" = "application/json")
+ 	req <- req %>% req_proxy(url = "gate.smartproxy.com",port = 7000,username = usname,password = uspwd)
+ 	resp <- req_perform(req)
+ 	message(fromJSON(resp_body_string(resp))$ip)
+ }
27.72.42.138
27.72.42.138
27.72.42.138
> 
> ## Ip Rotating
> library(RCurl)
> library(jsonlite)
> opts <- list(
+   proxy         = "gate.smartproxy.com",
+   proxyusername = usname, 
+   proxypassword = uspwd, 
+   proxyport     = 7000
+ )
> options(RCurlOptions = opts)
> for(idx in 1:3) message(fromJSON(getURL("https://ipinfo.io"))$ip)
122.2.115.248
45.112.69.9
182.239.85.49
````

Facing a similar [issue](https://github.com/r-lib/httr/issues/737) with httr & use_proxy as well.

**Comment by hadley** [comment]
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by yogesh-bansal** [comment]
I can't share the keys to make it a reproducible example, Though I figured a similar issue I was facing with the httr package as well.
The solution was to use the parameter 
`config(forbid_reuse = TRUE)` in the GET call to establish a new connection with each new call. Is there a similar config for the httr2 package?

Corresponding [issue](https://github.com/r-lib/httr/issues/737) with solution on httr package.

**Comment by hadley** [comment]
You could use `req_options()`
