### ISSUE TITLE
Support user-defined redaction in `req_headers()`

### ISSUE THREAD

**Issue by gvelasq** [r-lib/httr2#247]
The Google Cloud APIs use the [`x-goog-api-key` header](https://cloud.google.com/docs/authentication/api-keys#using-with-rest) to pass API keys. Currently, only the `Authorization` header is automatically redacted by `req_headers()`, as implemented in the internal function [headers_redact()](https://github.com/r-lib/httr2/blob/66c07ded035ae33ce2ed27f2c79a817286bcb1e8/R/headers.R#L44). `x-goog-api-key` is therefore not redacted:

``` r
library(httr2)

req_google <-
  request("https://www.googleapis.com") %>%
  req_url_path_append("youtube/v3") %>%
  req_headers("x-goog-api-key" = "ABC123XYZ")

req_google
#> <httr2_request>
#> GET https://www.googleapis.com/youtube/v3
#> Headers:
#> • x-goog-api-key: 'ABC123XYZ'
#> Body: empty
```
<sup>Created on 2023-06-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I recently added support for YouTube Data API key authentication in https://github.com/soodoku/tuber/pull/126, and it would be great to be able to redact the `x-goog-api-key` header used [here](https://github.com/soodoku/tuber/pull/126/files#diff-e746f18382d462bf758a3eb6f41f4c3e7dff6fafe019f17a5fab3f0d0dc75b29R180) for use in continuous integration. More broadly, a `.redact = TRUE` argument to `req_headers()` would permit users to redact any header. The desired behavior would look like the code block below:

``` r
library(httr2)

req_google <-
  request("https://www.googleapis.com") %>%
  req_url_path_append("youtube/v3") %>%
  req_headers("x-goog-api-key" = "ABC123XYZ", .redact = TRUE)

req_google
#> <httr2_request>
#> GET https://www.googleapis.com/youtube/v3
#> Headers:
#> • x-goog-api-key: '<REDACTED>'
#> Body: empty
```

**Comment by gvelasq** [comment]
Thank you, @mgirlich!

**Comment by mgirlich** [comment]
Happy to help 😄
