### ISSUE TITLE
Way to turn off cli progress bar during wait

### ISSUE THREAD

**Issue by misea** [r-lib/httr2#251]
When I use req_retry or req_throttle httr2 puts up a status bar for waits longer than 1 sec. This can mess up my other output and unless I set terminal settings explicitly makes some output unreadable. 

For instance, the image below is from a throttled output along with one req_retry in the RStudio background tabs pane interspersed with my output.

Would like an option to just turn this off.

<img width="691" alt="httr_output" src="https://github.com/r-lib/httr2/assets/8292064/b5815668-7044-4101-b280-d9f9416d5a68">

**Comment by hadley** [comment]
@gaborcsardi is this partly because cli isn't correctly detecting the features available in the background jobs pane?

**Comment by gaborcsardi** [comment]
If you call `cli_progress_bar()` then it will show a progress bar, independently of the features of the terminal. So if you don't want one, you either need to use `suppressMessages()` or have a switch in httr2 to turn it off. 

AFAICT there is no global switch in cli currently.

**Comment by hadley** [comment]
Oh duh, of course. I should check for `cli::is_dynamic_tty()`

**Comment by gaborcsardi** [comment]
Oh, AFAIR the output will be slightly different for non-dynamic ttys, so there will be no `\r`s, only `\n`s, but there will be output still. IMO the output is actually useful, but yeah, if you also have other output then it can mess things up.

**Comment by hadley** [comment]
This is slowly coming back to me. Shouldn't the output only appear once a second in a non-dynamic tty? But in the screenshot above it looks like it's appearing more than 1/s.

**Comment by hadley** [comment]
Ooooh I was thinking that the 20s should be counting down, but it's me that adds that, not the progress bar. Sorry for all the noise/confusion.

**Comment by misea** [comment]
Just to clarify, the background job isn't as important as when I start a long-running job with nohup and redirect the output to a file. In my desired case the output is readable without being 90% timing messages that add no value in this scenario.

**Comment by hadley** [comment]
Yup, got it.
