### ISSUE TITLE
Think about post-hoc retrieval of errorful responses

### ISSUE THREAD

**Issue by hadley** [r-lib/httr2#26]
i.e. from `last_error()$resp`; need to make sure that `oauth_flow_abort()` also includes

Consider redacting Authorization header.

**Comment by hadley** [comment]
Or maybe just always save last response?

**Comment by jennybc** [comment]
Here's what I'm currently doing in gargle:

https://github.com/r-lib/gargle/blob/0523266d3ba36d574eb18f197ac57f6699625e86/R/aaa.R#L18-L32

https://github.com/r-lib/gargle/blob/0523266d3ba36d574eb18f197ac57f6699625e86/R/response_process.R#L73-L78

https://github.com/r-lib/gargle/blob/0a2e7fd088c2ed52e088fe0d386f3d7adeac7d77/R/response_process.R#L197-L201
