### ISSUE TITLE
Consider clear_cache helper function

### ISSUE THREAD

**Issue by pbulsink** [r-lib/httr2#275]
It might be useful from time to time to have the ability to manually clear the cache with a single function call. 

May be related to #207 in implementation.

**Comment by hadley** [comment]
What are you looking for in such a function? I can't quite see how it would differ from `unlink(dir(cache_path, full.names = TRUE))`?

**Comment by pbulsink** [comment]
Yeah that would work fine. Maybe it could be mentioned in the docs for clarity?

**Comment by hadley** [comment]
Yeah, good idea.
