### ISSUE TITLE
`url_build` constructs invalid URL if `path` component does not start with `/`

### ISSUE THREAD

**Issue by jemus42** [r-lib/httr2#276]
Based off the documentation of `url_parse` I assumed it was intended for constructing a base URL and the modify individual components to assemble the desired URL, which led me to shoot myself in the foot a little when it came to the `path` component.

Consider the following example:

``` r
library(httr2)

test_url <- "https://example.com"
(test_url <- httr2::url_parse(test_url))
#> <httr2_url> https://example.com
#> • scheme: https
#> • hostname: example.com

test_url$path
#> NULL
test_url$path <- "somedir"
```

This results in an invalid URL, missing the `/` delimiter:

```r
test_url
#> <httr2_url> https://example.comsomedir
#> • scheme: https
#> • hostname: example.com
#> • path: somedir
```

 I expected `url_build` to detect/fix this, I guess?

```r
httr2::url_build(test_url)
#> [1] "https://example.comsomedir"
```

It's necessary to prepend the path with `/`

```r
test_url$path <- "/somedir"
# Valid URL
test_url
#> <httr2_url> https://example.com/somedir
#> • scheme: https
#> • hostname: example.com
#> • path: /somedir
```

I assumed appending the base URL with / would help, but it does not

```r
test_url <- "https://example.com/"
(test_url <- httr2::url_parse(test_url))
#> <httr2_url> https://example.com/
#> • scheme: https
#> • hostname: example.com
#> • path: /
test_url$path
#> [1] "/"
test_url$path <- "somedir"
httr2::url_build(test_url)
#> [1] "https://example.comsomedir"
```

<sup>Created on 2023-08-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by hadley** [comment]
Very minimal reprex using an internal function:

``` r
httr2:::url_modify("https://example.com/abc", path = "abc")
#> [1] "https://example.comabc"
```

<sup>Created on 2023-08-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
