### ISSUE TITLE
check_content_type() should correctly error when response has no content_type but suffix is checked. 

### ISSUE THREAD

**Issue by cderv** [r-lib/httr2#284]
This is issue is the same error as https://github.com/r-lib/httr2/issues/277 but in its minimal form. 

I stumbled upon this error while trying to do some mocking in testing with `httr2::response()`. 

````r
> httr2::resp_body_json(httr2::response())
Error in `if (!is.null(suffix) && endsWith(content_type, suffix)) ...`:
! missing value where TRUE/FALSE needed
Run `rlang::last_trace()` to see where the error occurred.
> rlang::last_trace()
<error/rlang_error>
Error in `if (!is.null(suffix) && endsWith(content_type, suffix)) ...`:
! missing value where TRUE/FALSE needed
---
Backtrace:
    ▆
 1. └─httr2::resp_body_json(httr2::response())
 2.   └─httr2:::check_content_type(...)
```` 

I don't think the error is very clear to understand is the call is really allowed or not. 

Simpler reprex:
```r
httr2:::check_content_type(httr2::response(), "application/json", suffix = "+json")
```

In there, 
https://github.com/r-lib/httr2/blob/7962bcd9aacd1cc71ee34c5e4fd3c0b8d172d670/R/resp-body.R#L130-L138
`content_type` can be `NA_character_`
https://github.com/r-lib/httr2/blob/d789827ce2795edbfac92ddaf3c3df5e33e85df4/R/resp-headers.R#L101-L107

and this will make `endsWith()` returns a NA
``` r
endsWith(NA_character_, "+json")
#> [1] NA
```

which is not good in the `if()` call and with `&&`

#277 was fixed by #278 but regarding the specific cache usage. 

I believe here the error should be clearer. Maybe `is.na(content_types)` should be checked also when `!is.null(suffix)` to handle this specific `content_types` value, and throw useful error.

**Comment by hadley** [comment]
Looks like this is fixed in #262:

```R
Error in `httr2::resp_body_json()`:
! Unexpected content type "NA"
• Expecting type "application/json", or suffix "json"
```
