### ISSUE TITLE
Consider renaming `resp_link_url()` to `resp_header_link()`

### ISSUE THREAD

**Issue by mgirlich** [r-lib/httr2#296]
As mentioned in https://github.com/r-lib/httr2/pull/279#discussion_r1303526156.

**Comment by hadley** [comment]
I've changed my mind on this given that the other functions for extracting specific headers don't use the `header` prefix. If I recall correctly, I was thinking that all data either comes from the headers or the body, so adding a header prefix to everything seemed unnecessary.
