### ISSUE TITLE
Multiple values for a search field: 2 methods return appropriate GET url's but not the same response

### ISSUE THREAD

**Issue by asadow** [r-lib/httr2#308]
I see appropriate GET url's but differing results when, for the same parameter, I specify A) multiple query parameters, or B) comma-separation.

A)
```
params <- list(
  date = I("<>07-03-2023,07-31-2023"),
  code = I("X,Y")
  )

names(params) <- toupper(names(params))

req <- httr2::request(url) |>
  httr2::req_url_path_append("timecard") |>
  httr2::req_url_query(!!!params)
```

`req` gives 

GET
https://api.myapi.com/uoft/dl/timecard?DATE=<>07-03-2023,07-31-2023&CODE=X,Y

vs.

B)
```
params <- list(
  date = I("<>07-03-2023,07-31-2023"),
  code = I("X"),
  code = I("Y")
  )

names(params) <- toupper(names(params))

req <- httr2::request(url) |>
  httr2::req_url_path_append("timecard") |>
  httr2::req_url_query(!!!params)
```

`req` gives

GET
https://api.myapi.com/uoft/dl/timecard?DATE=<>07-03-2023,07-31-2023&CODE=X&CODE=Y

The A method does not return data when performed (as if it is looking for code "X,Y" instead of both "X" and "Y"), where the B method does return data.

**Comment by hadley** [comment]
I'm not sure what your question is?

**Comment by asadow** [comment]
I thought this might be unexpected behaviour. Is it expected? Precisely, should GET url's with **CODE=SICK&CODE=CSICK** and **CODE=SICK,CSICK** give me different responses?

**Comment by hadley** [comment]
There's no guarantee that those two urls would give the same result. It would depend on the server.

**Comment by asadow** [comment]
Thanks, I had assumed REST API's would have standardization in this matter.
