### ISSUE TITLE
Broadly consider redaction

### ISSUE THREAD

**Issue by hadley** [r-lib/httr2#31]
When is a user likely to accidental leak confidential information when trying to get help?

* What else needs to be redacted apart from the Authorization header?
* Should `req_dry_run()` redact?
* Should `req_verbose()` redact?

**Comment by jennybc** [comment]
Based on some (arm's length) real world experience, the print method for an OAuth client (secret + id) should be a bit coy, i.e. strategically use `...`.

Otherwise, the main thing I handle that could potentially be a problem is persistent service account configuration (in the Google context). But I have not actually personally leaked or been witness to a leak.

**Comment by hadley** [comment]
``` r
library(httr2)
req <- httr2:::request_test("/get") 

req %>% req_auth_basic("username", "SECRET")
#> <httr2_request>
#> GET http://127.0.0.1:54999/get
#> Options:
#> • httpauth: 1
#> • userpwd: 'username:SECRET'
req %>% 
  req_auth_basic("username", "SECRET") %>% 
  req_dry_run(quiet = FALSE)
#> -> GET / HTTP/1.1
#> -> Host: 127.0.0.1
#> -> Authorization: Basic dXNlcm5hbWU6U0VDUkVU
#> -> User-Agent: httr2/0.0.0.9000 r-curl/4.3.1 libcurl/7.64.1
#> -> Accept: */*
#> -> Accept-Encoding: deflate, gzip
#> -> 

req %>% req_auth_bearer_token("SECRET")
#> <httr2_request>
#> GET http://127.0.0.1:54999/get
#> Headers:
#> • Authorization: 'Bearer SECRET'

client <- oauth_client("28acfec0674bb3da9f38", "SECRET")
client
#> <httr2_oauth_client> ID: 28acfec0674bb3da9f38 (confidental)
app <- oauth_app(client, endpoints = c(
  authorization = "https://github.com/login/oauth/authorize",
  token = "https://github.com/login/oauth/access_token"
))
req %>% req_oauth_auth_code(app)
#> <httr2_request>
#> GET http://127.0.0.1:54999/get
#> Policies:
#> • auth_oauth: a list
```

<sup>Created on 2021-06-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

So it looks like OAuth is already fine, but otherwise I need to:

* Switch `req_auth_basic()` to use same approach as `req_auth_bearer_token()`
* Automatically redact contents of Authorization header when printing
* Add option to `req_verbose()` (which powers `req_dry_run()`) to redact Authorization header

Then I can drop `req_redact()`, instead relying on redaction on print to avoid exposing confidential info.

**Comment by hadley** [comment]
Now:

``` r
library(httr2)
req <- httr2:::request_test("/get") 

req %>% req_auth_basic("username", "SECRET")
#> <httr2_request>
#> GET http://127.0.0.1:58597/get
#> Headers:
#> • Authorization: '<REDACTED>'
req %>% 
  req_auth_basic("username", "SECRET") %>% 
  req_dry_run(quiet = FALSE)
#> -> GET / HTTP/1.1
#> -> Host: 127.0.0.1
#> -> User-Agent: httr2/0.0.0.9000 r-curl/4.3.1 libcurl/7.64.1
#> -> Accept: */*
#> -> Accept-Encoding: deflate, gzip
#> -> Authorization: <REDACTED>
#> ->
req %>% req_auth_bearer_token("SECRET")
#> <httr2_request>
#> GET http://127.0.0.1:58597/get
#> Headers:
#> • Authorization: '<REDACTED>'
```

<sup>Created on 2021-06-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
