### ISSUE TITLE
Add `error` argument to `req_perform_iteratively()`

### ISSUE THREAD

**Issue by mgirlich** [r-lib/httr2#310]
In case a request fails it might still be interesting to continue (if possible) with the pagination or return the intermediate results.

**Comment by hadley** [comment]
There's possibly some connection to `cancel_on_error` on in `multi_req_perform()`.  We should probably also switch to using an enum for the reasons mentioned in https://design.tidyverse.org/explicit-strategies.html#only-two-strategies.

**Comment by mgirlich** [comment]
The error message when `parse_resp()` fails should also be improved.

**Comment by hadley** [comment]
Do you think we need to resolve this for the 0.3.0 release? (which I'd like to get out in around a month)

**Comment by mgirlich** [comment]
I think `req_paginate()` is already a nice addition even without an error handling argument in `paginate_req_perform()`. But we might want to rename `paginate_req_perform()` and change its interface, see the PR on `req_chunk()`: #307.

**Comment by hadley** [comment]
Maybe something like:

* `"error"` (the default): the iteration ends with an error.
* `"terminate"`: terminate the iteration and return progress
* `"continue"`: continue, ignoring the error

If you use `terminate` or `continue` the return value might be a mix of responses and errors, not just responses.

**Comment by mgirlich** [comment]
Sounds good to me.

**Comment by hadley** [comment]
I realised `continue` won't work for most of the iteration helpers (i.e. anything that depends on a request), and none of the error behaviours is terribly useful if we don't have a way to also track the response. I liked your idea of adding the request as attribute to the response, and maybe it makes sense to do that for the `httr2_failure` and `httr2_http` errors too.
