### ISSUE TITLE
Customise progress bar to `paginate_req_perform()`

### ISSUE THREAD

**Issue by mgirlich** [r-lib/httr2#311]

**Comment by hadley** [comment]
And pick between two options depending on whether or not total number of pages is known. Might want to abstract out the logic in `make_progress()` for this.

**Comment by mgirlich** [comment]
This currently looks like this:

* number of pages known
Paginate ■■■■                              10% | ETA: 34s

* number of pages not known
⠼ Paginate 5 done (0.93/s) | 5.4s

How should this look like in your opinion?
