### ISSUE TITLE
Add argument `max_elements` to `paginate_req_perform()`

### ISSUE THREAD

**Issue by mgirlich** [r-lib/httr2#313]
Usually, you are more interested in the number of elements than in the number of pages.
The difficulty is that this implies that we know the page size (e.g. specified in the `req_paginate()`) or can extract the number of elements from the response.

**Comment by hadley** [comment]
TBH I think we can just leave this until someone asks for it. The counter argument to using `max_elements` is that often you want to perform a specific number of requests, and you often won't want to throw away data if you get it for "free".
