### ISSUE TITLE
Error: 'req_paginate' is not an exported object from 'namespace:httr2' (and more...)

### ISSUE THREAD

**Issue by DavidRLovell** [r-lib/httr2#329]
After installing the latest version of R and the `httr2` package, I'm not able to access `req_paginate()` and related functions as described in [the current online `httr2` documentation](https://httr2.r-lib.org/reference/paginate_req_perform.html):

```
> library(httr2)
> req_paginate()
Error in req_paginate() : could not find function "req_paginate"
> httr2::req_paginate()
Error: 'req_paginate' is not an exported object from 'namespace:httr2'
> httr2:::req_paginate()
Error: object 'req_paginate' not found
> sessionInfo()
R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default


locale:
[1] LC_COLLATE=English_Australia.utf8  LC_CTYPE=English_Australia.utf8    LC_MONETARY=English_Australia.utf8
[4] LC_NUMERIC=C                       LC_TIME=English_Australia.utf8    

time zone: Australia/Brisbane
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] httr2_0.2.3

loaded via a namespace (and not attached):
[1] compiler_4.3.1 magrittr_2.0.3 R6_2.5.1       cli_3.6.1      tools_4.3.1    glue_1.6.2     rappdirs_0.3.3
[8] rlang_1.1.1  
```
PS. This is the first time I've ever posted an issue to github: please forgive me if this is inept and advise me how to do better.

PPS. `httr2` is amaaaaazing! It stands to deliver very positive benefits to me and my colleagues who need to access the Canvas Learning Management System API. I'm writing [lots of notes for myself at the moment](https://rpubs.com/DavidLovell/postman-httr2-baby-steps) ... if these could be made useful to others somehow, please let me know. I would like to give back to the `httr2` effort if I can.

**Comment by mgirlich** [comment]
`req_paginate()` was only added very recently and is only available in the dev version of httr2. Be aware that the interface of `req_paginate()` is currently still evolving and likely to be different to what it is right now.
But a new version of httr2 should soon be released and the interface should be a bit more stable then.

@hadley Should we have a pkgdown for the released and the dev version of httr2?

**Comment by hadley** [comment]
They're only available in the dev version at the moment. We're aiming to get it to CRAN in the next few weeks.

**Comment by hadley** [comment]
I've fixed the website so it now only shows the released function; you'll now need to go to <http://httr2.r-lib.org/dev/> to see the dev docs.

**Comment by DavidRLovell** [comment]
I’m so glad I got to see what was in development! I’ve given `req_paginate()` a thorough workout. Thanks for this excellent package!
