### ISSUE TITLE
req_url_query - modify_list error

### ISSUE THREAD

**Issue by lyndon-bird** [r-lib/httr2#356]
Hi,

I'm trying to pass in a list of parameters to a wrapper function that completes a request however I'm getting the error 

`Error in modify_list: All components of ... must be named`

Below is an example of using req_url_query with multiple parameters that works, and then the example that I'm trying to get to work as I was able to with httr. 

Any help would be appreciated.

Cheers,
Lyndon

```
library(httr2)

httr2::request("https://test.com") |> 
  httr2::req_url_query(start = "X", end = "Y")


req <- function(params) {
  httr2::request("https://test.com") |> 
    httr2::req_url_query(params) 
}

params <- list(start = "X", end = "Y")

req(params)

**Comment by mgirlich** [comment]
`req_url_query()` supports the so called dynamic dots. You can read about them in the documentation of `req_url_query()` or on the [rlang reference](https://rlang.r-lib.org/reference/dyn-dots.html). Give feedback if you don't understand how to apply them to your use case.

**Comment by mgirlich** [comment]
@hadley As we already check types we could also check if any of the arguments is a (bare) list and inform people about the dynamic dots. What do you think?

**Comment by hadley** [comment]
That just feels like overkill unless we notice multiple people hitting the same problem. It is documented and it is shown in one of the examples.

**Comment by lyndon-bird** [comment]
For the benefit of others I got it to work by splicing the list mentioned here [https://rlang.r-lib.org/reference/dyn-dots.html](rlang reference)

```
library(httr2)

req <- function(params) {
  httr2::request("https://test.com") |> 
    httr2::req_url_query(.multi='explode',!!!params) 
}

params <- list2(start = "X", end = "Y")

req(params)
