### ISSUE TITLE
httr json encoding of body works for POST but httr2 req_body_json does not work with jsonlite encoded named list

### ISSUE THREAD

**Issue by rressler** [r-lib/httr2#378]
Working with the USASpending by award API which requires a post query. The code below creates the body of the post and then converts the body to JSON.

- The httr2 query with the named listed converted to JSON returns a server error status 500.
- The httr POST query with the named list and encode="json" works fine - status 200 with good data.
- The httr POST query with the jsonlite encoded named list and encode = "raw" returns status 415.

Is httr encoding the json differently than the jsonlite::toJSON or is something else going on that I missed?

Thanks,
Richard

library(jsonlite)
library(httr2)
my_url <- "https://api.usaspending.gov/api/v2/search/spending_by_award/"
req <- request(my_url)
request_data <- list(
  "limit" = 5,
  "filters" = list(
    "award_type_codes" = c("A", "B")
  ),
  "fields" = c(
    "Award ID",
    "Recipient Name"
  )
)

request_data_json <- jsonlite::toJSON(request_data, auto_unbox = TRUE)

# Does not work, status 500
req |>
  req_body_json(data = request_data_json) |>
  req_perform()

# works fine
httr::POST(
  url = "https://api.usaspending.gov/api/v2/search/spending_by_award/",
  body = request_data,
  encode = "json"
)

# does not work - status 415
httr::POST(
  url = "https://api.usaspending.gov/api/v2/search/spending_by_award/",
  body = request_data_json,
  encode = "raw"
)

**Comment by lstanton428** [comment]
You don't need to format your `request_data` as JSON before using `req_body_json`. You can just do:

```
req |>
  req_body_json(data = request_data) |>
  req_perform()
```

**Comment by lstanton428** [comment]
I'm not sure if that answers your question, though. If you wanted format the JSON separately, you can use `req_body_raw` with `type = "application/json"`:

```
req |>
  req_body_raw(body = request_data_json, type = "application/json") |> 
  req_perform()
```

**Comment by rressler** [comment]
Thanks so much! I can see my interpretation of the help file was reversed! 

- req_body_json will encode the data into a JSON string using jsonlite and then send it.
- req_body_raw will take a JSON string and send it if the type is "application/json".

Now that I know that the help file makes more sense. It might benefit from a slightly revised statement for req_body_json and  few 
 more examples to demonstrate the different arguments and the need for "application/json" wiht req_body_raw. I was trying just "json".

The below both work fine.

Thanks!

req |>
  req_body_json(data = request_data) |>
  req_perform() ->
  tempp

req |>
  req_body_raw(body = request_data_json, type = "application/json") |>
  req_perform() ->
  tempp
