### ISSUE TITLE
Parallel + Iterative?

### ISSUE THREAD

**Issue by jonthegeek** [r-lib/httr2#381]
I'm exploring the multi-req options, and they made me wonder if it would be possible/advisable to combine req_perform_iterative() and req_perform_parallel() in some cases. For example, I could imagine getting paginated data for slightly different requests from a robust API in parallel. It's possible this would be a bad idea in many/most cases, so I can understand if you don't want to enable that sort of thing, but it could be useful.

A somewhat contrived, small example: house candidates from the FEC API.

To get more than 100 candidates, you need to use pagination:

```r
library(httr2)

req_base <- request("https://api.open.fec.gov/v1") |> 
  req_headers("X-Api-Key" = Sys.getenv("FEC_API_KEY", unset = "DEMO_KEY")) |> 
  req_url_path_append("candidates") |> 
  req_url_query(office = "H", per_page = 100)

house_2020_resps <- req_base |>
  req_url_query(election_year = 2020) |> 
  req_perform_iterative(
    iterate_with_offset(
      "page",
      resp_pages = \(resp) {
        resp_body_json(resp)$pagination$pages
      }
    ),
    max_reqs = Inf
  )

house_2020 <- house_2020_resps |> 
  resps_data(\(resp) resp_body_json(resp)$results)
```

I can imagine performing that set of requests for multiple years. I might do something like this:

```r
house_2018_2022 <- purrr::map(
  2018 + 0:2*2,
  \(year) {
    req_url_query(req_base, election_year = year)
  }
) |> 
  req_perform_parallel(
    but_also_iterative_for_each()
  )
```

Would that be something you would want to support?

**Comment by hadley** [comment]
We considered this in the design but there are currently a lot of limitations to parallel requests that make it less compelling. This is something we could reconsider in a couple of years once the API settles.
