### ISSUE TITLE
`req_template` cannot mix templates with both colon (:) and curly brackets ({ })

### ISSUE THREAD

**Issue by stefanedwards** [r-lib/httr2#389]
The Microsoft Graph API has some curious endpoints, one of which requires the use of colon (`:`)

```HTTP
GET /sites/{hostname}:/{server-relative-path}
```
https://learn.microsoft.com/en-us/graph/api/site-get?view=graph-rest-1.0&tabs=http#access-a-site-by-server-relative-url

`req_template` fails miserable, as it believes the template uses colon-placeholders - not curly bracket placeholders:

```
req_template(request("http://example.http.com"), "/sites/{hostname}:/{server-relative-path}")
Error in env_has(env, name, inherit = TRUE) : 
  attempt to use zero-length variable name
```

# Suggested solutions:

1. Document this behaviour, *most do*.
2. In `template_type` swap two first if conditions, so curly brackets are checked first, then brackets. Downside: Using a template without placeholders, but with a colon in the path will still fail.
3. Check for `:\\w+` in the grepl for colon, instead of just `:`.

I'll gladly make the changes and make a pull request.

**Comment by stefanedwards** [comment]
Workaround:

Provide the colon in a variable placeholder.

```
req_template(request("http://example.http.com"), "/sites/{hostname}{colon}/{server-relative-path}", colon = ":")
```

**Comment by hadley** [comment]
I think flipping the check for colon and braces templates should do the job.
