### ISSUE TITLE
oauth vignette is an article

### ISSUE THREAD

**Issue by jonthegeek** [r-lib/httr2#398]
Several help docs mention `vignette("oauth")`, but that vignette is only available on the website. Trying to load it throws a warning, and doesn't do anything:

``` r
vignette("oauth", package = "httr2")
#> Warning: vignette 'oauth' not found
```

<sup>Created on 2023-11-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I'm not certain yet whether it would be as simple as moving the vignette out of articles, or if that vignette can't build and the help docs instead need to be tweaked (or if I have something configured strangely to cause the error in the first place).

**Comment by hadley** [comment]
It would be better to fix the docs.
