### ISSUE TITLE
Something to manually clear auth cache

### ISSUE THREAD

**Issue by hadley** [r-lib/httr2#405]
Occasionally useful to clear session cache manually, like when you revoke the a token from the GitHub API.

Should also consider if need someway to register a custom "you should reauth now" handler (i.e. to customise `resp_is_invalid_oauth_token`). GitHub doesn't appear to follow the spec, so I bet other APIs don't either.

**Comment by jennybc** [comment]
Does httr2 have a oauth sitrep function? Along the lines of `gargle_oauth_sitrep()`. That has paid off over there, both during development and for solving user mysteries. I'm sure it would look different for httr2, but maybe something in the same spirit would be useful.

https://gargle.r-lib.org/reference/gargle_oauth_sitrep.html

https://gargle.r-lib.org/articles/troubleshooting.html#gargle_oauth_sitrep

**Comment by jmaspons** [comment]
Fixed with https://github.com/r-lib/httr2/commit/8e9f8588e66378f1f419158cd1810a82a4dad022 ?

**Comment by hadley** [comment]
Oh yeah, thanks!
