### ISSUE TITLE
Advice on conflicts between testthat and httr2 for mocks?

### ISSUE THREAD

**Issue by fh-mthomson** [r-lib/httr2#419]
``` r
library(testthat)
library(httr2)
#> 
#> Attaching package: 'httr2'
#> The following objects are masked from 'package:testthat':
#> 
#>     local_mock, with_mock
```

<sup>Created on 2023-12-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by hadley** [comment]
Don't attach both packages at once 😄 

(I'm not sure what else I can do here; `local_mock()` and `with_mock()` are already deprecated but I can't remove for a while without breaking CRAN packages)

**Comment by fh-mthomson** [comment]
😂 that actually makes sense. It came up while attaching `httr2` while developing tests for another package. In reality, `testthat` isn't something we'd attach in non-testing code, anyway. Thanks!
