### ISSUE TITLE
Mask Authorization in print method if provided

### ISSUE THREAD

**Issue by fh-mthomson** [r-lib/httr2#420]
Trying to replicate [httr approaches to interacting with the Connect API](https://docs.posit.co/connect/cookbook/#r-with-httr) in `httr2` highlighted that the API key is printed directly to the console when building up the request:

``` r
library(httr2)
request("https://r-project.org") |>
  req_headers("Authorization" = paste("Key", "SECRET"))
#> <httr2_request>
#> GET https://r-project.org
#> Headers:
#> • Authorization: 'Key SECRET'
#> Body: empty
```

<sup>Created on 2023-12-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mgirlich** [comment]
You have to explicitly specify that the header should be redacted via the `.redact` argument:

```r
req_headers("Authorization" = paste("Key", "SECRET"), .redact = "Authorization")
```

We considered automatically redacting certain headers but decided against it.
