### ISSUE TITLE
proposal: demo projects

### ISSUE THREAD

**Issue by mstei4176** [r-lib/httr2#422]
Dear `httr2` Maintainers,

I am writing to propose an enhancement to the `httr2` package's documentation and demo resources. The `httr` package currently hosts a [demo project folder](https://github.com/r-lib/httr/tree/main/demo), which serves as an invaluable resource for users trying to understand and implement various functionalities. This feature greatly aids in the practical understanding of the package's capabilities.

In a similar vein, I believe that the `httr2` package could benefit significantly from the inclusion of OAuth demos, besides the build-in Github project, specifically for LinkedIn and other widely-used services. OAuth authentication is a common requirement for many modern web APIs, and clear, concise examples in this area would be a substantial resource for users of the `httr2` package.

The proposed demos could cover common OAuth workflows, handling tokens, and practical examples of making authenticated requests to popular services like LinkedIn. This addition would not only enhance the learning experience for new users but also serve as a quick reference guide for more experienced users working with OAuth in R.

I understand that maintaining and updating documentation requires effort and time, and I am willing to help testing the demos  if needed. I believe this enhancement aligns well with the `httr2` project's goals of making HTTP requests straightforward and user-friendly.

Thank you for considering this suggestion. I am looking forward to any feedback or thoughts on this proposal.

Best regards,
Martin

**Comment by hadley** [comment]
IMO vignettes are uniformly better than demos because they're included in the pkgdown site, run automatically, and can include explanatory text more easily. But automatically running OAuth demos adds a large maintenance penalty to the package because it forces me to figure out what's changed whenever those demos break.

That said, more realistic examples in https://httr2.r-lib.org/articles/oauth.html would be useful, so if there are specific APIs that you think pose particular challenges that aren't currently covered well by the vignette, I'd love to hear about them.

**Comment by mstei4176** [comment]
That's fair and I agree that maintainability is an important factor, so examples via vignettes would be great. 

Linkedin for example. 

I have this httr code - and it is working fine:

```
linkedin <- oauth_endpoint(
    authorize = "https://www.linkedin.com/oauth/v2/authorization",
    access = "https://www.linkedin.com/uas/oauth2/accessToken"
  )
  
  r_client_id = linkedin_id
  r_redirect_uri = "http://localhost:1410/"
  r_scope = "r_basicprofile w_member_social"
  r_client_secret = linkedin_secret
  r_nonce <- as.numeric(as.POSIXct(Sys.time()))
  
  oauth_app(appname="myapp", key=r_client_id, secret = r_client_secret, redirect_uri = r_redirect_uri) -> linkedin_app
  
  oauth2.0_token(
    endpoint= linkedin,
    app=linkedin_app,
    scope = r_scope,
    user_params = NULL,
    type = NULL,
    use_oob = FALSE,
    #oob_value = linkedin_app$redirect_uri,
    as_header = TRUE,
    use_basic_auth = FALSE,
    cache = getOption("httr_oauth_cache"),
    config_init = list(),
    client_credentials = FALSE,
    credentials = NULL,
    query_authorize_extra = list()
  ) -> at2
```
What is the httr2 equivalent? I run into issues with setting scope and auth_params for the Linkedin API.
```
Sys.setenv("HTTR2_OAUTH_REDIRECT_URL" = "http://localhost:1410/")

client <- httr2::oauth_client(
    id = linkedin_id,
    token_url = "https://www.linkedin.com/uas/oauth2/accessToken",
    auth = "header",
    name = "myapp"
)

token <- httr2::oauth_flow_auth_code(
  client = client,
  auth_url = "https://www.linkedin.com/uas/oauth2/authorization?response_type=code",
  scope = "r_basicprofile w_member_social",
  auth_params = list("grant_type" = "authorization_code",  "client_secret" = linkedin_secret)
)
```
And a related question how do I manage Linkedin authentication (for example) when executing from a hosted shiny app?

**Comment by hadley** [comment]
This worked for me:

```R
library(httr2)

client <- oauth_client(
  id = "8601emhempk9ku",
  token_url = "https://www.linkedin.com/uas/oauth2/accessToken",
  secret = obfuscated("Z2X5MhUPQo7NQ22aUmN0uOnkZUynNzGcmCwcLAU5kcY"),
  name = "httr2-test-app",
)

token <- oauth_flow_auth_code(
  client = client,
  auth_url = "https://www.linkedin.com/uas/oauth2/authorization",
  scope = "w_member_social",
  redirect_uri = "http://localhost:1410",
  pkce = FALSE
)
```

I think there are two key changes from your code:

* LinkedIn uses the default ("body") auth mechanism so I dropped the `auth` argument from `oauth_client`
* LinkedIn doesn't appear to support PKCE, and disabling it seemed to be the key to getting everything working

We have yet to fully figure out how to use OAuth from a shiny app, but what exactly are you trying to do? Do you want to authenticate as the author of the shiny app, or do you want each user of the shiny app to provide their own credentials?

**Comment by mstei4176** [comment]
Thanks for the code check, Hadley. 

I would like users of my shiny app to provide their own credentials. Like a having a "Connect" button that gives my app permission to use their LinkedIn account for certain tasks.

**Comment by hadley** [comment]
@mstei4176 I'm slightly mystified that works for you for in a hosted environment, but I've probably just forgotten the details.

That auth scenario is #47; I think in principle we know how to make it work, but we've been unable to get it finished because it requires me + Joe + Jenny to all have OAuth loaded up in our heads at the same time 😞.

**Comment by mstei4176** [comment]
@hadley
1) The flow worked on my **local** RStudio environment. The LinkedIn login page comes up and, after finishing authentication, the flow continues in my Shiny app - running in a local browser. Seems all good here. 
2) If I recollect correctly the same happened in my **hosted** RStudio Server environment, but I would have to double-check when I have access to it next week.
3) I don't have access to Posit Connect for testing it, so can't comment on the flow.
4) The flow did not work when I used a containerized app. 

I can test env cases 2), 3) and 4) next week when I am back home and share what happens.

**Comment by hadley** [comment]
Closing since I think we're tracking the shiny auth issue elsewhere, and I'm sceptical that I can explain enough about OAuth debugging in a vignette to really help anyone.
