### ISSUE TITLE
datetime format in req_url_query() params

### ISSUE THREAD

**Issue by tony2015116** [r-lib/httr2#423]
**This is my code:**
params <- list(location_min = "103", location_max = "103", date_min = "2024-01-02T16:00:00Z", date_max = "2024-01-02T16:00:00Z")
login_response <- login_request |>
  req_url("https://XXXXX.com") |>
  req_url_query(generate = "1", !!!params)

**If my date_min/date_max are set as follows:**
 date_min = "2024-01-02T16:00:00Z", date_max = "2024-01-02T16:00:00Z"

**It will return:**
  "https://XXXXX.com?generate=1&location_min=103&location_max=103&date_min=2024-01-02T16%3A00%3A00Z&date_max=2024-01-02T16%3A00%3A00Z"
![image](https://github.com/r-lib/httr2/assets/26536471/20fcf138-6775-41e4-aecd-e3d8a28d9bc8)

**But my API like this:**
  "https://XXXXX.com?generate=1&location_min=103&location_max=103&date_min=01-02T16:00:00Z&date_max=2024-01-02T16:00:00Z"

And what should I set in req_url_quey() params about this datetime format?

**Comment by hadley** [comment]
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by tony2015116** [comment]
Thanks! I've found the real reason why the scraping wasn't working, and it's not an issue with the 'date_min' and 'date_max' format in the parameters. Thank you again for developing such a useful R package!
![image](https://github.com/r-lib/httr2/assets/26536471/3a84dcf4-14eb-4643-a1db-bedc4bfd4b06)
