### ISSUE TITLE
`req_timeout()` overrides `req_error()`

### ISSUE THREAD

**Issue by CareCT** [r-lib/httr2#424]
Hello,

I thought that by setting `req_error(req, is_error = \(x) FALSE)` would not raise an error in an `httr2` request, even by setting a very low timeout.

However this example does raise an error:

```
library(httr2)

request("https://duckduckgo.com?q=hello") |>
    req_error(is_error = \(x) FALSE) |>
    req_timeout(0.001) |>
    req_perform()
```

Is this an intended feature or a bug?

Cheers and thanks for this great package,

Andrea

**Comment by hadley** [comment]
This is expected — `req_error()` only handles how HTTP errors (e.g. 40x/50x status codes) are converted to R errors; the timeout error indicates that the request never successfully completed. See https://httr2.r-lib.org/reference/req_error.html#error-handling for more details, and some tools you can use to handle these sorts of error.

**Comment by CareCT** [comment]
Thanks for your quick reply!
