### ISSUE TITLE
Support empty headers

### ISSUE THREAD

**Issue by pmlefeuvre-met** [r-lib/httr2#428]
Hi,

I am trying to set up a cursor pagination protocol following the rules attached below and using `httr2::req_perform_iterative()`. I therefore started to build my own [next_req()](https://httr2.r-lib.org/reference/req_perform_iterative.html?q=pagi#next-req-) function, but I struggle to get a response and also to extract my cursor from the headers instead of the body. Would you have some pointers on how to integrate that kind of cursor? 

```R
next_req <- function(resp, req){
  header <- resp$headers$`X-Frost-Nextptsheader`
  if (is.null(header))
    return(NULL)
  headers <- list("X-Frost-Ptsheader" = header,
                  "X-Frost-Ptsbaseid" = resp$headers$`X-Frost-Nextptsbaseid`,
                  "X-Frost-Ptime" = resp$headers$`X-Frost-Nextptsptime`)
  req |> req_headers(!!!headers)
}

resp <- request("https://havvarsel-frost.met.no/api/v1/obs/glider/get") |>
  req_url_query(
    incobs = "true",
    itemlimit = "100",
    time = "2020-10-07T09:00:00Z/2020-10-07T10:00:00Z") |>
  req_headers("X-Frost-Ptsheader" = "")  |>
  req_perform_iterative(next_req())
```
I currently do not even go beyond a missing response: `Error in next_req() : argument "resp" is missing, with no default`. To debug, I have tried to play around `req_perform(verbosity=1)` but I am not able to pass an empty header with `req_headers("X-Frost-Ptsheader" = "")` and thus get a 403 Forbidden error.

Thanks for your help,
PiM

---
The pagination rules, I try to follow:
> ## First request
> To initiate the protocol, the client simply ensures that the first request has the HTTP header `X-Frost-Ptsheader` set to an empty string.
> ## Last response
> To indicate the final page, Frost sets the HTTP header `X-Frost-Ptsnextheader` in the response to an empty string.
> ## General/intermediate request-response
> Upon receiving a response R with a non-empty `X-Frost-Ptsnextheader`, the headers of the next request must be set from the headers of R as follows:
>     `X-Frost-Ptsheader` set to value of `X-Frost-Nextptsheader`
>     `X-Frost-Ptsbaseid` set to value of `X-Frost-Nextptsbaseid`
>     `X-Frost-Ptime` set to value of `X-Frost-Nextptime`

---
I attach a curl example with the headers (below) that I need to set the pagination:
```
...
> GET /api/v1/obs/glider/get?incobs=true&itemlimit=100&time=2020-10-07T09%3A00%3A00Z%2F2020-10-07T10%3A00%3A00Z HTTP/2
> Host: havvarsel-frost.met.no
> user-agent: curl/7.81.0
> accept: */*
> x-frost-ptsheader:
...
< x-frost-nextptime: 1602064747
< x-frost-nextptsbaseid: {"source": "University of Bergen", "gliderid": "6801614", "parameter": "sea_water_salinity"}
< x-frost-nextptsheader: H4sIAAAAAAAA/xSMwarCMBQFf6WcdRav0FckS//BdbnaY7iQpnITqyXk3yW7YRimQg7RKPdI+Noc+C0m8BVJNsIjh/95QnPQtdsQdaV1xnz5G+dxgsNLTDYWWu8py0cKbckSNWk54ZD3tz367Zb0oGUt57A/hystMKG1HwAAAP//AQAA//+v3bONhgAAAA==
...
```
The extracted header lines come from the curl request:
```shell
curl -v -H "X-Frost-Ptsheader;" "https://havvarsel-frost.met.no/api/v1/obs/glider/get?incobs=true&itemlimit=100&time=2020-10-07T09%3A00%3A00Z%2F2020-10-07T10%3A00%3A00Z" -w '\n' 
*   Trying 157.249.74.82:443...
* Connected to havvarsel-frost.met.no (157.249.74.82) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS header, Finished (20):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.2 (OUT), TLS header, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=havvarsel-frost.met.no
*  start date: Dec  3 07:13:00 2023 GMT
*  expire date: Mar  2 07:12:59 2024 GMT
*  subjectAltName: host "havvarsel-frost.met.no" matched cert's "havvarsel-frost.met.no"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* Using Stream ID: 1 (easy handle 0x55df478ed780)
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
> GET /api/v1/obs/glider/get?incobs=true&itemlimit=100&time=2020-10-07T09%3A00%3A00Z%2F2020-10-07T10%3A00%3A00Z HTTP/2
> Host: havvarsel-frost.met.no
> user-agent: curl/7.81.0
> accept: */*
> x-frost-ptsheader:
> 
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
< HTTP/2 200 
< cache-control: max-age=86400
< content-type: application/json
< x-frost-nextptime: 1602064747
< x-frost-nextptsbaseid: {"source": "University of Bergen", "gliderid": "6801614", "parameter": "sea_water_salinity"}
< x-frost-nextptsheader: H4sIAAAAAAAA/xSMwarCMBQFf6WcdRav0FckS//BdbnaY7iQpnITqyXk3yW7YRimQg7RKPdI+Noc+C0m8BVJNsIjh/95QnPQtdsQdaV1xnz5G+dxgsNLTDYWWu8py0cKbckSNWk54ZD3tz367Zb0oGUt57A/hystMKG1HwAAAP//AQAA//+v3bONhgAAAA==
< date: Wed, 24 Jan 2024 14:57:36 GMT
< 
* TLSv1.2 (IN), TLS header, Supplemental data (23):
{
   "data": {
      "tstype": "glider",
       ...
   }
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Connection #0 to host havvarsel-frost.met.no left intact
}
```

**Comment by hadley** [comment]
I think the main problem is that you're calling `next_req()` instead of just passing it in, e.g.:

```R
...  |>
  req_perform_iterative(next_req)
```

I'd also recommend using `resp_header()` to get the request headers rather than relying on the internal implementation details, and I do think you can make it a little simpler by eliminating the intermediate list.  Something like this:

```R
next_req <- function(resp, req) {
  header <- resp_header(resp, "X-Frost-Nextptsheader")
  if (is.null(header))
    return(NULL)

  req |> req_headers(
    "X-Frost-Ptsheader" = header,
    "X-Frost-Ptsbaseid" = resp_header(resp, "X-Frost-Nextptsbaseid"),
    "X-Frost-Ptime" = resp_header(resp, "X-Frost-Nextptsptime")
  )
}
```

**Comment by pmlefeuvre-met** [comment]
Thanks @hadley, your suggestion solves the missing response error. 

The remaining issue is how to parse an empty header  to initiate the API pagination, I see that it conflicts with httr2/curl's behaviour. Indeed, setting a header value to `""`, removes the header as explained in the `req_headers()` [doc](https://httr2.r-lib.org/reference/req_headers.html?q=req_headers#null). This is in line with curl behaviour, however curl has a work around to set an empty header using `;` such as: `curl -H "X-Frost-Ptsheader;"`. Here is an example with the request output that I had my earlier comment:

```shell
...
curl -v -H "X-Frost-Ptsheader;" "https://havvarsel-frost.met.no/api/v1/obs/glider/get?incobs=true&itemlimit=100&time=2020-10-07T09%3A00%3A00Z%2F2020-10-07T10%3A00%3A00Z" -w '\n' 
> GET /api/v1/obs/glider/get?incobs=true&itemlimit=100&time=2020-10-07T09%3A00%3A00Z%2F2020-10-07T10%3A00%3A00Z HTTP/2
> Host: havvarsel-frost.met.no
> user-agent: curl/7.81.0
> accept: */*
> x-frost-ptsheader:
...
```
So I am wondering if it is a behaviour that you would like to have in httr2? We do manage to parse an empty header in python using the [requests library](https://requests.readthedocs.io): 
```python
headers = {'X-Frost-Ptsheader': ''}  # initialize protocol
r = requests.get(url, headers=headers)
```

For info, we are also discussing also replacing the empty header needed to initialise the pagination to a defined string.

Thanks for your help and a great package!

**Comment by pmlefeuvre-met** [comment]
I also see that an empty header is skipped in `httr2::curl_translate()`:
```
httr2::curl_translate("curl -v -H \"X-Frost-Ptsheader;\" \"https://havvarsel-frost.met.no/api/v1/obs/glider/get?incobs=true&itemlimit=100&time=2020-10-07T09%3A00%3A00Z%2F2020-10-07T10%3A00%3A00Z\" ")
  
  request("https://havvarsel-frost.met.no/api/v1/obs/glider/get") |> 
    req_url_query(
      incobs = "true",
      itemlimit = "100",
      time = "2020-10-07T09:00:00Z/2020-10-07T10:00:00Z",
    ) |> 
    req_perform(verbosity = 1)
  ```

**Comment by hadley** [comment]
Hmmmm, I'm not sure you can even set an empty header in the curl package. Let me look into this.

**Comment by hadley** [comment]
The curl package doesn't support this in `handle_setheader()`, but can use `handle_setopt(httpheader, headervec)` with manually constructed string. Just need to figure out what this should look like on the R side.

**Comment by hadley** [comment]
I think the easiest way is probably to allow `req_header(req, foo = " ")` to send an empty header, but if you do have control over the API I'd strongly encourage you to use specific value rather than an empty header. You're the first user of curl/httr/httr2 who has needed to set an empty header, so it seems like a pretty unusual API design.

**Comment by pmlefeuvre-met** [comment]
Yes, I understand, we have come up with an alternative string to initialise pagination and it works like a charm.

**Comment by hadley** [comment]
Ok, I'll still fix this in httr2 in case it ever comes up again, but it'll be fairly low on my to do list.

**Comment by pmlefeuvre-met** [comment]
Agree
