### ISSUE TITLE
req_error() modify status code 

### ISSUE THREAD

**Issue by JosiahParry** [r-lib/httr2#439]
In a similar vein to https://github.com/r-lib/httr2/issues/98.

I have a badly behaved server that will return errors as json. I'd like to use `req_error()` to catch these and abort appropriately. However, I'd like to be able to specify the status_code that the error is thrown with. Here, for example, `!HTTP 200 OK.` is printed. 
Is it possible to change the status_code that is shown there? I've tried modifying the status code in the response but that does not work.

``` r
library(httr2)
request("http://example.com") |>
  req_error(is_error = \(.x) TRUE, body = \(.x) {
    .x$status_code <- 404L
  }) |> 
  req_perform()
#> Error in `req_perform()`:
#> ! HTTP 200 OK.
#> • 404
#> Backtrace:
#>     ▆
#>  1. └─httr2::req_perform(...)
#>  2.   └─httr2:::handle_resp(req, resp, error_call = error_call)
#>  3.     └─httr2:::resp_abort(resp, req, body, call = error_call)
#>  4.       └─rlang::abort(...)
```

<sup>Created on 2024-02-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by sckott** [comment]
what about

```r
with_mocked_responses(\(req) response(status_code = 404), {
  request("http://example.com") |>
    req_perform()
})
#> Error in `req_perform()`:
#> ! HTTP 404 Not Found.
```

**Comment by JosiahParry** [comment]
Thank you @sckott ! This seems promising. Though, I'm struggling to catch up b/c the docs are a bit outdated (examples refer to `with_mock()` which isn't exported). Essentially, my goal is to capture the output code here `resp$error$code` and pass that in. I _think_ `with_mocked_response()` can get us there? I'm just not sure whats available in the scope of the body 🤔 💭 

``` r
library(httr2)
furl <- "https://services.arcgis.com//0?f=json"
req <- request(furl)
req_perform(req) |> 
  resp_body_json()
#> $error
#> $error$code
#> [1] 400
#> 
#> $error$message
#> [1] "Invalid URL"
#> 
#> $error$details
#> $error$details[[1]]
#> [1] "Invalid URL"
```

**Comment by hadley** [comment]
I think you're better handling this at a higher level, i.e. using `tryCatch()` to return the modified request. Otherwise I'm worried that this would grew the scope of `req_error()` too much.
