### ISSUE TITLE
Proposal: glue notation in req_url_path(_append)

### ISSUE THREAD

**Issue by jonthegeek** [r-lib/httr2#443]
`req_template()` supports glue syntax, but loses the composability of `request() |> req_url_path_append()`. But paths are often also documented with glue-like syntax. For example, the apis.guru api has a `/{provider}.json` path, where `provider` is a path parameter (and the [OpenAPI spec](https://spec.openapis.org/oas/v3.1.0#parameter-object) specifically allows such `path` parameters).

At first I thought this would need a new function, but in theory `req_url_path()` and `req_url_path_append()` could treat *named* arguments as `path` parameters, making these equivalent:

```r
request("https://api.apis.guru/v2") %>% 
  req_url_path_append("googleapis.com.json")
```

```r
request("https://api.apis.guru/v2") %>% 
  req_url_path_append("{provider}.json", provider = "googleapis.com")
```

It looks like only `dots_to_path` would need to be updated, and the tests look robust enough that it could be done safely, I think. I could probably whip up a PR if this sounds reasonable.

**Comment by jennybc** [comment]
gh has some code related to this, which came in https://github.com/r-lib/gh/pull/121.

**Comment by hadley** [comment]
I think you've missed `req_template()`:


``` r
library(httr2)

request("https://api.apis.guru/v2") %>% 
  req_template("{provider}.json", provider = "googleapis.com")
#> <httr2_request>
#> GET https://api.apis.guru/v2/googleapis.com.json
#> Body: empty
```
