### ISSUE TITLE
Ability for auto_unbox to apply element wise

### ISSUE THREAD

**Issue by jmuhlenkamp** [r-lib/httr2#452]
Hello!  I am currently working with an API that requires some body items to be a JSON scalar and others to be a JSON array even if there is only one element in the array.  Is this easily supported with httr2?

 ```
library(httr2)

req <- request(example_url()) |>
  req_url_path("/post")
```

I can easily generate all scalars via
```
req |>
  req_body_json(list(globalId = 9, localId = c(1)), auto_unbox = TRUE) |>
  req_dry_run()
```
which creates the body as `{"globalId":9,"localId":1}`

OR I can easily generate all arrays via
```
req |>
  req_body_json(list(globalId = 9, localId = c(1)), auto_unbox = FALSE) |>
  req_dry_run()
```
which creates the body as `{"globalId":[9],"localId":[1]}`

The API I am working with is refusing my requests unless I create the body as `{"globalId":9,"localId":[1]}`  Is there a way to achieve this in the reprex above with httr2?

Thanks in advance!  Any insights here are very much appreciated!

**Comment by hadley** [comment]
Here are two options:

``` r
library(httr2)

request(example_url()) |>
  req_body_json(list(globalId = 9, localId = I(c(1))), auto_unbox = TRUE) |>
  req_dry_run()
#> POST / HTTP/1.1
#> Host: 127.0.0.1:63143
#> User-Agent: httr2/1.0.0 r-curl/5.2.1 libcurl/8.4.0
#> Accept: */*
#> Accept-Encoding: deflate, gzip
#> Content-Type: application/json
#> Content-Length: 28
#> 
#> {"globalId":9,"localId":[1]}

request(example_url()) |>
  req_body_json(list(globalId = jsonlite::unbox(9), localId = c(1)), auto_unbox = FALSE) |>
  req_dry_run()
#> POST / HTTP/1.1
#> Host: 127.0.0.1:63143
#> User-Agent: httr2/1.0.0 r-curl/5.2.1 libcurl/8.4.0
#> Accept: */*
#> Accept-Encoding: deflate, gzip
#> Content-Type: application/json
#> Content-Length: 28
#> 
#> {"globalId":9,"localId":[1]}
```

<sup>Created on 2024-03-08 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

Either use `I()` to force boxing or `unbox()` to force unboxing.

**Comment by jmuhlenkamp** [comment]
Perfect!  Thank you, Hadley!
