### ISSUE TITLE
Figure out how to update curlconverter

### ISSUE THREAD

**Issue by hadley** [r-lib/httr2#453]
https://curlconverter.com/

**Comment by llrs** [comment]
It seems it is in https://github.com/curlconverter/curlconverter/blob/master/src/generators/r.ts.

**Comment by mgirlich** [comment]
I added a draft PR to curlconverter: https://github.com/curlconverter/curlconverter/pull/675. @hadley would be great if you could have a look if the generated httr2 code makes sense to you.

**Comment by hadley** [comment]
@mgirlich will do, hopefully some time next week.

**Comment by hadley** [comment]
Thanks for working on this! I took a quick look and gave some initial feedback.

**Comment by mgirlich** [comment]
curlconverter is updated now :smiley:

**Comment by hadley** [comment]
Thank you!
