### ISSUE TITLE
#NICAR24

### ISSUE THREAD

**Issue by walinchus** [r-lib/httr2#457]
![IMG_0129](https://github.com/r-lib/httr2/assets/25959269/51fc6cc6-5b7f-4155-aca3-4f00b57ce9b3)

Could someone please post this presentation from @hadley Wickham to this repository when you get a chance? I thought it was very useful at NICAR24 and I didn't have a chance to copy the whole thing. Thank you!

**Comment by hadley** [comment]
You can find it at https://github.com/hadley/talk-httr2
