### ISSUE TITLE
URL encoding oddities

### ISSUE THREAD

**Issue by jl5000** [r-lib/httr2#461]
When I submit a request with a username and password, URL encoding seems to happen inconsistently.

I've used `example_url()` below as a placeholder, but it doesn't show the issue.

```
request(example_url()) |> 
  req_options(httpauth = 4L, userpwd = ":::") |> 
  req_perform()
```

This will give a response where the URL is `https://:%3a%3a@....`

If I then try

```
request(example_url()) |> 
  req_options(httpauth = 4L, username = ":", password = ":") |> 
  req_perform()
```

It will give a response where the URL is `https://%3a:%3a@....`

I've tried to produce a reprex for this but I don't know how.

**Comment by hadley** [comment]
This is a pretty thin wrapper over libcurl, so you'll probably need to direct your questions there. I have zero experience with "HTTP Negotiate (SPNEGO) authentication"
