### ISSUE TITLE
HTTP/2 stream 1 was not closed cleanly before end of the underlying stream

### ISSUE THREAD

**Issue by IshuaWang** [r-lib/httr2#462]
hi, I use the lib but sometime find the error above. Sorry that I can't fix the problem myself. I don't know why this happens and how to fix it. Could you give me some advice? The following is the information:

```
Backtrace:
     ▆
  1. ├─global get_column_data("RS_V1_0", c("subjectKey"))
  2. │ └─... %>% resp_body_json()
  3. ├─httr2::resp_body_json(.)
  4. │ └─httr2:::check_response(resp)
  5. │   └─httr2:::is_response(req)
  6. └─httr2::req_perform(.)
  7.   └─base::tryCatch(...)
  8.     └─base (local) tryCatchList(expr, classes, parentenv, handlers)
  9.       └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 10.         └─value[[3L]](cond)
```

 **get_column_data** is my function.

**Comment by IshuaWang** [comment]
ok, I know this is may be caused by curl package in buggy server.

**Comment by hadley** [comment]
Unfortunately there's no much I can do without a reprex, but given that the error is coming from curl, I think you're correct that this is likely to be due to a buggy server.
