### ISSUE TITLE
manual abort in presence of retry-after header

### ISSUE THREAD

**Issue by krjaworski** [r-lib/httr2#466]
In line with documentation:

 _**If the response contains the Retry-After header, httr2 will wait the amount of time it specifies.** If the API you are wrapping conveys this information with a different header (or other property of the response) you can override the default behaviour with retry_after_

The API that I’m connecting to indeed has such header. However, in a presence of such header, the req_perform() does not actually return an explicit error (or a response) that I could catch. The function just automatically starts to wait. From the user perspective, it seems as if the R just freezes (in my case for 15 minutes) without any explicit information.

Is there a way to return an explicit “Too many requests” error in the presence of “retry-after” header? Or perform a manual abort? I would like to use it to switch the API key to a new one( that has not yet reached a request limit) and continue to access the API without having to wait.

**Comment by hadley** [comment]
Can you provide a reprex? From inspecting the code, it looks like you should get a progress bar that counts down the timer.

If you don't want to retry when you get a header, then you don't need to use `req_retry()`?
