### ISSUE TITLE
Error thrown on timeout, even when error handling is requested

### ISSUE THREAD

**Issue by MarekGierlinski** [r-lib/httr2#467]
I want to suppress errors when accessing a database URL. In most cases I can achieve this by using `req_error(is_error = ~FALSE)`. However, when there is a server timeout, the following code actually throws an error:

```
resp <- request("http://www.google.com:81") |>
  req_error(is_error = ~FALSE) |>
  req_perform()
Error in `req_perform()`:
! Failed to perform HTTP request.
Caused by error in `curl::curl_fetch_memory()`:
! Timeout was reached: [www.google.com:81] Failed to connect to www.google.com port 81 after 10001 ms: Timeout was reached
```

which makes my code crash every time there is a timeout. Is this a feature or a bug? How can I control timeout errors (apart from explicitly using `tryCatch()`)?

**Comment by hadley** [comment]
`req_error()` only controls the behaviour of errors caused by requests with failing status codes. If you want to handle timeouts, you can use the error handling techniques mentioned in the docs: https://httr2.r-lib.org/reference/req_error.html#error-handling.
