### ISSUE TITLE
Self-signed certificates

### ISSUE THREAD

**Issue by i2z1** [r-lib/httr2#468]
While testing request to my service with self-signed certificate (fot testing purposes only!) I've got this error

```
Caused by error in `curl::curl_fetch_memory()`:
! SSL peer certificate or SSH remote key was not OK: [api-key.***.com] SSL certificate problem: self-signed certificate in certificate chain
```
Is it able to pass via httr2  a custom parameter to underlying `curl`, so it can ignore self-signed certificates?
It seems usefull for testing purpose.

**Comment by hadley** [comment]
Yes, you can use `req_options()`: https://httr2.r-lib.org/reference/req_options.html
