### ISSUE TITLE
Automatically remove old tokens

### ISSUE THREAD

**Issue by hadley** [r-lib/httr2#48]
I think it makes sense to have some default expiration policy, so that tokens that haven't been used for x days (maybe default to 30?) are automatically deleted.

**Comment by hadley** [comment]
Can't easily set on a per client basis, because if client isn't used, then what would trigger the delete? So maybe 30 days since creation?

**Comment by hadley** [comment]
Now deleting 30 days post creation; can revisit if needed.

**Comment by jennybc** [comment]
👀 I think this will upset some folks' apple cart. But it could also help to keep people a little bit more in touch with their tokens, how they got them in the first place, and encourage more appropriate flows for non-interactive work.

I assume you've seen this:

https://developers.google.com/identity/protocols/oauth2#5.-refresh-the-access-token,-if-necessary.

> Save refresh tokens in secure long-term storage and continue to use them as long as they remain valid. Limits apply to the number of refresh tokens that are issued per client-user combination, and per user across all clients, and these limits are different. If your application requests enough refresh tokens to go over one of the limits, older refresh tokens stop working.

It will be interesting to see if there's ever any downside or push back to the 30-day purge, based on more distant consequences, i.e. for other tokens the user has obtained.

**Comment by jennybc** [comment]
Oh maybe this just affects access tokens (vs. refresh)? Is this just deleting token that have probably already expired anyway?

**Comment by hadley** [comment]
This is deleting any old token, regardless of whether or not it's expired.

**Comment by jennybc** [comment]
Should they be revoked, then deleted?

**Comment by hadley** [comment]
Revocation is something that only google seems to support. I think deleting is adequate.
