### ISSUE TITLE
both wrappers httr2::jwt_encode_sig and httr2::jwt_encode_hmac call jose::jwt_encode_sig

### ISSUE THREAD

**Issue by denskh** [r-lib/httr2#508]
This causing error when trying to use jwt_encode_hmac: 
https://github.com/r-lib/httr2/blob/023c535c8584ffdd518b278015c0a95b2ca3553c/R/jwt.R#L70

**Comment by hadley** [comment]
Ooops. Do you want to do a PR to fix this?
