### ISSUE TITLE
Example for `req_cache()` usage in package

### ISSUE THREAD

**Issue by m-muecke** [r-lib/httr2#513]
`req_cache()` already has an example with using `tempdir()` as the path, would be great to have an example for using it with `tools::R_user_dir("pgk", "cache")` like done in the pkgdown package and others

**Comment by hadley** [comment]
What sort of example are you looking for?

**Comment by m-muecke** [comment]
Currently the docs mention using `unlink(dir(cache_path, full.names = TRUE)` or `tempdir()` for the path arg. Would be great to have a sentence or example for using it inside a package with `tools::R_user_dir`. Perhaps something similar to what I've found in the pkgdown package:

```r
req_pkgdown_cache <- function(req) {
  cache_path <- dir_create(path(tools::R_user_dir("pkgdown", "cache"), "http"))
  httr2::req_cache(
    req,
    path = cache_path,
    max_age = 86400 # 1 day
  )
}
```
