### ISSUE TITLE
Checking content type

### ISSUE THREAD

**Issue by mgirlich** [r-lib/httr2#58]
In `resp_body_json()` the only accepted media type seems to be `application/json`. Many APIs have vendor specific types, e.g. `application/vnd.github-issue.text+json` (see other examples on [Swagger](https://swagger.io/docs/specification/media-types/#names) or the [RFC 6838](https://datatracker.ietf.org/doc/html/rfc6838#section-4.2.8)).
It would be great if these media types were also recognized as valid json media type.

**Comment by hadley** [comment]
Nice! I didn't know this was a standard.
