### ISSUE TITLE
How to implement a modified "explode" option for `.multi` in `req_url_query()`?

### ISSUE THREAD

**Issue by Aariq** [r-lib/httr2#593]
I'm working with the [usa-npn API](https://docs.google.com/document/d/1yNjupricKOAXn6tY1sI7-EwkcfwdGUZ7lxYv7fcPjO8/edit?tab=t.0#heading=h.7alfzd42opt9) which takes multiple values for a query like so: `x[1]=1&x[2]=2&x[3]=3`.  The `.multi` argument doesn't seem to be able to handle this and I have to construct the list of queries outside of `req_url_query()`.  It seems like there isn't a way for a function supplied to `.multi` to use the parameter name.  E.g., this doesn't work:

``` r
library(httr2)

#this sort of thing would be nice
foo <- function(x) {
  x_name <- deparse(substitute(x))
  glue::glue("{x_name}[{seq_along(x)}]={x}") %>% 
    glue::glue_collapse(sep = "&")
}
ID <- 5:7
foo(ID)
#> ID[1]=5&ID[2]=6&ID[3]=7

#but doesn't work here
request("https://example.com") %>% 
  req_url_query(
    ID = 5:7,
    .multi = foo
  )
#> <httr2_request>
#> GET https://example.com?ID=X[[i]][1]=5&X[[i]][2]=6&X[[i]][3]=7
#> Body: empty
```

<sup>Created on 2024-12-09 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

Is there a workaround for this? I looked at the code to figure out what `"explode"` does, and it seems like it behaves differently from an anonymous function—I couldn't figure it out.

**Comment by hadley** [comment]
There's no way to do it currently with `.multi` because it assumes that the names stay the same. You could however do something like this:

```R
library(httr2)

foo <- function(nm, vals) {
  setNames(vals, paste0(nm, "[", seq_along(vals), "]"))
}
request("https://example.com") |>
  req_url_query(!!!foo("ID", 5:7))

```

**Comment by Aariq** [comment]
Thanks! That is a much "cleaner" solution than I had before

**Comment by hadley** [comment]
BTW does it still work with your API if you omit the index? i.e. `x[]=1&x[]=2&x[]=3

**Comment by Aariq** [comment]
> BTW does it still work with your API if you omit the index? i.e. `x[]=1&x[]=2&x[]=3`. If so you could do:
> 
> ```
> request("https://example.com") %>% 
>   req_url_query(
>     `ID[]` = 5:7,
>     .multi = "explode"
>   )
> ```

I have no idea why, but that *does* work (at least for the endpoint I tested).  Thanks for the suggestion!
