### ISSUE TITLE
Export req_policies? 

### ISSUE THREAD

**Issue by jonthegeek** [r-lib/httr2#603]
I'd like to extend httr2 for by setting policies for pagination and response parsing while creating a request, so users can "leave" my package(s) to do normal httr2 things, but then my opinionated perform and parse can figure out what to do. Setting policies seems like the most logical way to do this. Would you consider exporting `req_policies()` as a clean api for extensions? It looks relatively straightforward, so I can implement my own version if necessary, but it would be nice to take advantage of any future safety improvements or whatever.

I'll knock out a more concrete examen of what I'm looking to do when I'm off the road, but wanted to put this idea out there. I could also PR this if you think it's a good idea. 

Thanks again for the package!

**Comment by hadley** [comment]
I'm pretty sure that this is best kept as an internal feature as I don't want to deal with the namespacing issues that arise if we were to allow anyone to write into this data structured.
