### ISSUE TITLE
End iteration for blank cursor

### ISSUE THREAD

**Issue by jonthegeek** [r-lib/httr2#612]
`iterate_with_cursor()` checks that the next cursor is NULL. I've had to build in a check to convert empty strings `""` to `NULL`, for example for the Slack API. Would it be acceptable to build that into the default checker? 
https://github.com/r-lib/httr2/blob/main/R%2Fiterate-helpers.R#L100

The same idea likely also occurs for `iterate_with_link_url()`.

**Comment by hadley** [comment]
Can you point me to the docs or show an example?

**Comment by jonthegeek** [comment]
You can kinda see it in the example response here: https://api.slack.com/methods/admin.apps.requests.list

I'll pull up specific examples when I'm back on my laptop.

**Comment by jonthegeek** [comment]
And this is where I clean it up: https://github.com/jonthegeek/slackapi/blob/main/R%2F040-pagination.R
