### ISSUE TITLE
"User-supplied key" section should explain how to provide secrets interactively

### ISSUE THREAD

**Issue by yutannihilation** [r-lib/httr2#73]
["User-supplied key" section](https://httr2.r-lib.org/articles/wrapping-apis.html#user-supplied-key-1) of the vignette says

> A good place to start is an environment variable, because environment variables are easy to set without typing anything in the console (which can get accidentally shared via your `.Rhistory`)

While I generally agree with the idea, I believe a package should also provide some measure to input secrets interactively, for example askpass package. I'd argue encouraging the use of an environmental variable cannot stop the users who want to try the functionality quickly; if the envvar is the only way to do so, they can easily type `Sys.setenv(YOURPACKAGE_KEY = "xxx")` in the console directly, which is not the consequence we wanted. So, how about adding these lines?

``` diff
  if (is_testing()) {
    testing_key()
+ } else if(interactive()) {
+   key <- askpass::askpass("NYTIMES_KEY")
  } else {
    stop("No API key found, please supply with `api_key` argument or with NYTIMES_KEY env var")  
  }
```

(Further, I prefer not to expose such an argument like `api_key`, but it's probably rather my personal preference.)

**Comment by yutannihilation** [comment]
Btw, maybe `testing_key()` should be assigned to `key`? (or `return()`ed early?)

**Comment by hadley** [comment]
I don't love the idea of prompting the user to copy and paste a password every time they make a request — I think that's a better fit if you do some systematic management of the key (which I think is what you're alluding to when you say you prefer not to have an `api_key` argument). I'll see if I have the energy to document that strategy now; otherwise it'll need to wait for the next release.

(Thanks for spotting the error in `testing_key()`; I'll fix momentarily)

**Comment by hadley** [comment]
Maybe I can take a compromise position and just mention that you might want to do provide a helper for setting the key:

```R
set_api_key <- function(key) {
  key <- key %||% askpass::askpass("Please enter your API key")
  Sys.setenv("NYTIMES_KEY" = key)
}
```

This obviously won't persist across multiple sessions, but it makes life easier for the newer user.

**Comment by yutannihilation** [comment]
Ah, yes, I set the input as the corresponding envvar all the time. Looks good, thanks for the improvement!
