### ISSUE TITLE
Using a proxy

### ISSUE THREAD

**Issue by gregleleu** [r-lib/httr2#77]
Couldn't find it in the documentation, is there a translation of use_proxy yet?
I would imagine something along the lines of
```
req <- req %>% req_use_proxy(url = ..., port = ..., ...)
```

**Comment by jjfantini** [comment]
I am currently experiencing issues with having to use `httr::use_proxy `with `httr2 ` , is there a work around to set a proxy up and use HTTP request logic from `httr2`?

**Comment by owenjonesuob** [comment]
For the moment, I don't think there's a dedicated function for this like there was in {httr} - but we can pass the necessary options straight through to curl using `httr2::req_options()`. The following format works for me, for a proxy which doesn't require authentication:
```r
req <- httr2::request("http://www.example.com") %>%
  httr2::req_options(proxy = "http://proxyaddress", proxyport = 1234)
```

If your proxy _does_ require auth, I _think_ (going by the [curl docs](https://curl.se/libcurl/c/CURLOPT_PROXYUSERPWD.html)) you could specify `proxyuserpwd` too in the format `"user:pass"` - though I haven't found a way to test this myself! If you're running this code interactively you could use {askpass} to avoid hard-coding your password, something like:
```r
req <- httr2::request("http://www.example.com") %>%
  httr2::req_options(
    proxy = "http://proxyaddress",
    proxyport = 1234,
    proxyuserpwd = paste0("myname", ":", askpass::askpass())
  )
)
```

Probably not too tricky to wrap this up into a `req_use_proxy()` function as suggested. In fact that's more or less what `httr::use_proxy()` seems to do! Maybe I'll open a PR... 🤔

**Comment by jjfantini** [comment]
I think that's a great solution, well worth implementing!
