### ISSUE TITLE
parsed csv with ";" delimiter

### ISSUE THREAD

**Issue by selesnow** [r-lib/httr2#80]
Hello!

Could you help me, how i can parsed csv answer with ";" delimiter in `httr2`?

Example in `httr`
```
ans <- GET('https://api.com')
content(ans, as = 'parsed', type = "text/csv")
```

**Comment by hadley** [comment]
1. that code is httr, not httr2. 
2. retrieve the data with `resp_body_string()` and parse how you normally would
