### ISSUE TITLE
Does httr2 automatically cache OAuth tokens on disk?

### ISSUE THREAD

**Issue by hongooi73** [r-lib/httr2#81]
I'm now exploring how to convert AzureAuth to use httr2.

IIRC, httr cached the tokens it obtained. Does httr2 have the same behaviour? On trawling through the source, I found a reference to `rappdirs::user_cache_dir("httr2")`, which on my machine expands to `C:\\Users\\hongo\\AppData\\Local/httr2/httr2/Cache`. However I don't see a directory at that location after obtaining a token.

**Comment by hadley** [comment]
It can, but doesn't do so by default — you need to opt-in by setting `cache_disk = TRUE` in `req_oauth_auth_code()` and friends.

**Comment by hongooi73** [comment]
Thanks!
