### ISSUE TITLE
Documentation should mention the default method for a request

### ISSUE THREAD

**Issue by hongooi73** [r-lib/httr2#83]
I inferred that the default is GET for a request without a body, and POST if a body is present, but it would be good not to have to find this out by trial and error.

**Comment by hadley** [comment]
You can also use `req_dry_run()`, but agreed that the docs should be better. Not sure where to put it. At a minimum should go in `req_method()`.

**Comment by hongooi73** [comment]
I would probably mention it in `?req`:

> The default HTTP method for a new request, or a request without a body, is GET. If a request body is present, the default method is POST.
