### ISSUE TITLE
Response of Content-Type: application/zip

### ISSUE THREAD

**Issue by KoderKow** [r-lib/httr2#86]
Hello!

I wanted to start off by saying that this package is amazing, it has simplified a lot of the code I have written for a wrapper package for the API I am working with!

The endpoint I am requesting data from will either return the response with content type `text/csv` or `application/zip`.  I can handle the `text/csv` fine, but I am having a hard time on knowing the smoothest way to work with a zip response.

So my question is, what is the recommended way of working with a zip response? I am interested in knowing if there is a way to save and then unzipor if I can unzip to obtain the data directly from the response.

I do not have reprex setup since there are accounts and keys involved.

Thanks!

**Comment by hadley** [comment]
I'd suggest saving the file to disk and then using either `unzip()` or https://archive.r-lib.org/index.html.

**Comment by KoderKow** [comment]
I am familiar with saving to disk using `httr::write_disk()`, is there a method setup in {httr2}? I do not know if the API will send a zip or csv before making the request so I think I need to decide what to do with the response object. I am struggling with what to do when I have the resp object that has the data in zip format, output example below with URL removed.

```r
> resp
#> <httr2_response>
#> GET
#> {HOST_URL}train.csv.zip
#> Status: 200 OK
#> Content-Type: application/zip
#> Body: In memory (97809929 bytes)
```

Can I get help on writing the body thats in memory to a zip so I can then unzip it? I have not worked with this type of return before. Here is copy/paste of the body

```r
resp$body
#>   [1] 50 4b 03 04 2d 00 00 00 08 00 ea 6a fd 52 91 b1 e4 f0 ff ff ff ff ff ff
#>  [25] ff ff 09 00 14 00 74 72 61 69 6e 2e 63 73 76 01 00 10 00 83 4b 87 0c 00
#>  [49] 00 00 00 6d 75 d4 05 00 00 00 00 3c fd 49 8e 64 cb b2 b3 89 f6 63 2a cf
#>  ...
```

Appreciate the help! Thanks for sharing the {archive} package, that looks amazing!

**Comment by KoderKow** [comment]
Got it working with `writeBin()` and {archive}, good to go 💯

**Comment by hadley** [comment]
You can also use the `path` argument to `req_perform()` to save directly to disk.
