### ISSUE TITLE
Device Code Grant with PKCE

### ISSUE THREAD

**Issue by m-mohr** [r-lib/httr2#92]
Some providers (e.g. EGI check-in) support Device Code with PKCE (as in Auth Code with PKCE). This is useful in some circumstances and we'd like to use it instead of AuthCode with PKCE to avoid (1) spinning up a server in the background and (2) providing a client secret. Are there any plans to implement Device Code with PKCE? If not, would you be open to a PR?

**Comment by flahn** [comment]
Please have a look at the PR  #109. I have implemented and tested the device code flow + PKCE against the [EGI service](https://www.egi.eu/services/check-in/) which we use in the [openEO projects](https://openeo.cloud/).
