### ISSUE TITLE
SAML authentication?

### ISSUE THREAD

**Issue by jl5000** [r-lib/httr2#96]
Is it possible to use the package to authenticate via SAML? If not, are there any plans to?

**Comment by hadley** [comment]
Can you point me to a technical specification of what SAML over HTTP means?

**Comment by jl5000** [comment]
The best I can find is at https://wiki.oasis-open.org/security/FrontPage. I'm really sorry, but the technical background to this is way beyond my comprehension. I just know that its required to access the MediaWiki API, but beyond that the whole topic is opaque to me.

**Comment by atheriel** [comment]
Wikipedia has [a pretty in-depth article on SAML](https://en.wikipedia.org/wiki/SAML_2.0). It's hard for anyone to comprehend! While it is true that SAML authentication is "just" sending HTTP requests with XML bodies, actually implementing these flows in R with `httr2` and an XML package like `xml2` would be very tedious, especially if SAML's encryption features get involved. You are probably signing up to do a ton of debugging.

I'm not aware of an existing R package to do proper SAML auth flow, either, so I'd probably recommend using another tool or language and, if necessary, calling that from R instead. For what it's worth, SAML is really uncommon for API authentication (though it *is* common for web-based applications), which is probably why this hasn't come up before.
