### ISSUE TITLE
Stacking queries in req_url_query()

### ISSUE THREAD

**Issue by jl5000** [r-lib/httr2#97]
In some APIs, such as for [Jive](https://developers.jivesoftware.com/api/v3/cloud/rest/index.html), you can **stack** query parameters with the same name and differentiate them in the values, however the default behaviour of `httr2` seems to be to overwrite them if they have the same name, e.g.:

`httr2::req_url_query(req, filter = "name(Hadley)", filter = "company(rstudio)")`

Would it be worth adding a parameter to switch off this behaviour?

**Comment by lmkirvan** [comment]
I'll second this. It looks like the default is only to take the second of two query parameters with the same name. Even if you don't want to allow this behavior for some reason, I think adding a warning that one is being dropped make sense.

**Comment by hadley** [comment]
Reprex:

``` r
library(httr2)

request("https://test.com") |> 
  req_url_query(filter = "X", filter = "Y") 
#> <httr2_request>
#> GET https://test.com?filter=Y
#> Body: empty
```

<sup>Created on 2022-04-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
