### ISSUE TITLE
Error handing with status 200

### ISSUE THREAD

**Issue by selesnow** [r-lib/httr2#98]
Hello, 

I try to use `req_error()` for handing next respons:

```
<httr2_response>
GET https://api.tgstat.ru/usage/stat?token=asdfghjklkjhgfd
Status: 200 OK
Content-Type: application/json
Body: In memory (42 bytes)
```

```
resp_body_json(resp)
$status
[1] "error"

$error
[1] "token_invalid"
```

And i try use
```r
tg_error_body <- function(resp) {
  resp %>% resp_body_json() %>% .$error
}

tg_is_error <- function(resp) {
  resp_stat <- resp %>% resp_body_json() %>% .$status
  resp_status(resp) == 200 && resp_stat == "error"
}

resp <- request(str_glue('{getOption("tg.base_url")}')) %>%
    req_url_path_append(method) %>%
    req_url_query( token  = 'False access token') %>%
    req_user_agent("rtgstat") %>%
    req_retry(
      max_tries    = getOption('tg.max_tries'),
      is_transient = ~ !is_response(.x) && resp_status(.x) != 200,
      after        = getOption('tg.interval')
    ) %>%
    req_error(is_error = function(resp) TRUE, body = tg_error_body) %>%
    req_perform() %>%
    resp_body_json()
```

And it does not work, could you help, how i can handing error response with status 200?

# minimal reprex

```r
request("http://httpbin.org/") %>%
  req_error(is_error = function(resp) TRUE) %>%
  req_perform()

<httr2_response>
GET http://httpbin.org/
Status: 200 OK
Content-Type: text/html
Body: In memory (9593 bytes)
```

**Comment by hongooi73** [comment]
That seems to be a badly behaved server. If the request failed, it should **not** return a status code of 200; httr2 is doing the right thing and saying that there was no error.

Rather than using `req_error` or any of the usual tools for error handling, you should just parse the body of the response and look for an "error" component.

**Comment by hadley** [comment]
@hongooi73 the server is badly behaved, but httr2 is supposed to be able to handle this sort of bad behaviour.

**Comment by selesnow** [comment]
> Rather than using req_error or any of the usual tools for error handling, you should just parse the body of the response and look for an "error" component.

At the moment I am doing so

```r
  if ( resp$status  == 'error' ) {
    cli_abort(resp$error)
  }
```

But I think that API can give error messages in different ways, including, as in my example, return an error with a 200 status, and it would be logical to add the ability to process such responses to `httr2`.

**Comment by hadley** [comment]
The problem is at https://github.com/r-lib/httr2/blob/main/R/req-perform.R#L110 because `resp_check_status()` returns early if `!resp_is_error(resp)`. Probably need to split this up into two functions.
